export const MANCHETES = {
  // 1. O RICO (Cash King)
  RICO: [
    { titulo: "CAPA DA FORBES", corpo: "${nome} foi eleito a personalidade do ano. 'O segredo é acordar cedo e herdar terrenos', diz o magnata que acumula R$ ${saldo}." },
    { titulo: "PISCINA DE DINHEIRO", corpo: "Vizinhos relatam que ${nome} mandou instalar um trampolim no cofre forte para mergulhar em suas moedas de ouro." },
    { titulo: "PROBLEMAS DE RICO", corpo: "${nome} reclamou de dores nas costas por carregar uma carteira tão pesada. A fisioterapia será paga à vista." },
    { titulo: "OSTENTAÇÃO", corpo: "${nome} foi visto usando notas de dinheiro como guardanapo. 'É mais absorvente', declarou o milionário." },
    { titulo: "COMPRA DA CIDADE?", corpo: "Com R$ ${saldo} na conta, ${nome} perguntou o preço da Prefeitura. O prefeito negou a venda, por enquanto." },
    { titulo: "TÉDIO MILIONÁRIO", corpo: "${nome} está tão rico que contratou alguém para jogar os dados por ele. 'Cansa muito o pulso', afirmou." },
    { titulo: "NOVO BANCO?", corpo: "O Banco Central estuda pedir um empréstimo para ${nome} para fechar o caixa do ano. A liquidez dele é impressionante." },
    { titulo: "CHUVA DE PRATA", corpo: "${nome} jogou moedas para a plebe da sacada de seu hotel. O trânsito parou com a confusão." },
    { titulo: "COFRE LOTADO", corpo: "A segurança foi reforçada na casa de ${nome}. Dizem que ele guarda o PIB de um pequeno país debaixo do colchão." },
    { titulo: "SEM TROCO", corpo: "${nome} tentou comprar um chiclete com uma nota de 500 e o jornaleiro teve um infarto. 'Só ando com notas altas', desculpou-se." },
    { titulo: "CLUBE EXCLUSIVO", corpo: "${nome} fundou um clube onde só entra quem tem saldo acima de 4 dígitos. Até agora, só ele é sócio." },
    { titulo: "DOAÇÃO RECUSADA", corpo: "${nome} tentou doar dinheiro para abater a dívida externa, mas o sistema do governo não aceitou tantos zeros." },
    { titulo: "CARRO DE OURO", corpo: "Boatos de que ${nome} encomendou um carro banhado a ouro. 'Combina com meus dentes', teria dito o magnata." },
    { titulo: "ALMOÇO CARO", corpo: "${nome} gastou o equivalente ao aluguel de um mês em um único jantar e nem pediu a nota fiscal paulista." },
    { titulo: "INFLAÇÃO PESSOAL", corpo: "A presença de ${nome} no bairro fez o preço do pãozinho subir. A economia gira em torno dele agora." },
    { titulo: "REI DO CAMAROTE", corpo: "Todas as festas da cidade esperam por ${nome}. Ele agrega valor ao camarote e paga a conta de todo mundo." },
    { titulo: "LIMITE INFINITO", corpo: "O cartão de crédito de ${nome} não tem limite, tem horizonte. Ele comprou uma ilha no débito." },
    { titulo: "SÓ VOO PRIVADO", corpo: "${nome} se recusa a pisar no chão comum. Só se desloca de helicóptero entre suas propriedades." },
    { titulo: "COLECIONADOR DE ARTE", corpo: "${nome} comprou a Mona Lisa original para pendurar no banheiro. 'Ficou bom com o azulejo', comentou." },
    { titulo: "PETISCO DE LUXO", corpo: "O cachorro de ${nome} só come ração importada servida em tigela de cristal. A vida de cão nunca foi tão boa." },
    { titulo: "SEGURANÇA MÁXIMA", corpo: "${nome} anda cercado por 10 seguranças. Não pelo perigo, mas para carregar as sacolas de compras." },
    { titulo: "PAPEL DE PAREDE", corpo: "${nome} redecorou a sala colando notas de 100 na parede. Disse que saiu mais barato que papel de parede importado." },
    { titulo: "ESMOLA GENEROSA", corpo: "${nome} deu uma gorjeta que dava para comprar um carro popular. O garçom se aposentou na hora." },
    { titulo: "ROUPAS DESCARTÁVEIS", corpo: "${nome} não lava roupa. Usa uma vez e doa. Diz que 'água estraga o tecido'." },
    { titulo: "TEMPO É DINHEIRO", corpo: "${nome} contratou alguém para dormir por ele. A ciência diz que é impossível, mas ele paga bem." },
    { titulo: "SORRISO BRILHANTE", corpo: "${nome} colocou diamantes nos dentes. Agora ele não pode comer pipoca, mas o sorriso ofusca a todos." },
    { titulo: "MUSEU PARTICULAR", corpo: "${nome} abriu um museu com seus extratos bancários. A exposição 'A Ascensão de um Império' é sucesso." },
    { titulo: "NOME DE RUA", corpo: "${nome} quer comprar o direito de renomear a Avenida Paulista para 'Avenida ${nome}'. A prefeitura está considerando." },
    { titulo: "LIVRO DE AUTOAJUDA", corpo: "${nome} lançou o livro 'Como ser eu'. Tem apenas uma página escrita: 'Tenha dinheiro'." },
    { titulo: "FESTA NA LUA", corpo: "${nome} está financiando o programa espacial só para dar a primeira festa de aniversário em gravidade zero." }
  ],

  // 2. O POBRE (Broke)
  POBRE: [
    { titulo: "VAQUINHA ONLINE", corpo: "Amigos de ${nome} organizam vaquinha. 'Ele tentou pagar um café com uma nota de banco imobiliário e foi recusado'." },
    { titulo: "ALMOÇO GRÁTIS?", corpo: "Com saldo de R$ ${saldo}, ${nome} foi visto rondando a praça de alimentação esperando alguém deixar sobra de lanche." },
    { titulo: "DORMIDAS NA RUA", corpo: "Sem dinheiro para aluguéis, ${nome} foi visto negociando abrigo na caixa de papelão da geladeira nova do vizinho." },
    { titulo: "DIETA FORÇADA", corpo: "Com apenas R$ ${saldo} na conta, ${nome} anunciou que viverá de fotossíntese até a próxima rodada." },
    { titulo: "VENDE-SE ALMOÇO", corpo: "${nome} está vendendo o almoço para pagar a janta. Interessados devem entrar em contato antes que ele coma o produto." },
    { titulo: "SALDO NO VERMELHO", corpo: "O gerente do banco ligou para ${nome} apenas para rir. A situação é crítica e requer um milagre." },
    { titulo: "CATANDO MOEDAS", corpo: "${nome} foi visto revirando o sofá da sala de espera do banco em busca de moedas perdidas." },
    { titulo: "ROUPA EMPRESTADA", corpo: "${nome} pediu emprestado um terno para ir na entrevista de emprego, mas a entrevista era para ser palhaço." },
    { titulo: "ÁGUA COM AÇÚCAR", corpo: "${nome} está servindo água com açúcar como 'drink gourmet' nas festas para economizar." },
    { titulo: "SEM CRÉDITO", corpo: "${nome} tentou parcelar uma coxinha em 12 vezes e teve o cartão recusado por saldo insuficiente." },
    { titulo: "NETFLIX CORTADA", corpo: "${nome} está assistindo novela na TV do vizinho usando um binóculo porque cortaram sua internet." },
    { titulo: "CARONA SOLIDÁRIA", corpo: "${nome} está oferecendo carona de bicicleta na garupa em troca de um salgado." },
    { titulo: "BANHO DE CANECA", corpo: "Cortaram a água de ${nome}. Ele está tomando banho na fonte da praça central de madrugada." },
    { titulo: "VENDE-SE TUDO", corpo: "${nome} colocou o próprio rim à venda na OLX. O anúncio foi removido, mas o desespero continua." },
    { titulo: "WI-FI DO VIZINHO", corpo: "${nome} foi pego tentando adivinhar a senha do Wi-Fi da padaria para atualizar o LinkedIn." },
    { titulo: "MIOJO GOURMET", corpo: "${nome} lançou um livro de receitas: '1001 maneiras de fazer Miojo render'. Best-seller na crise." },
    { titulo: "CALOTE NO ÔNIBUS", corpo: "${nome} tentou passar por baixo da catraca do ônibus e ficou entalado. O motorista pagou a passagem por pena." },
    { titulo: "FESTA DO PÃO", corpo: "${nome} deu uma festa onde o prato principal era pão com ar. 'É leve e não engorda', disse ele." },
    { titulo: "SÓ OLHANDO", corpo: "${nome} entrou no shopping só para aproveitar o ar condicionado. Foi expulso por 'olhar demais' para as vitrines." },
    { titulo: "CELULAR TIJOLÃO", corpo: "${nome} teve que vender o smartphone e voltar a usar um Nokia 1100. Pelo menos tem o jogo da cobrinha." },
    { titulo: "REI DO FIADO", corpo: "${nome} tem conta pendurada em todas as padarias do bairro. Seu rosto está em cartazes de 'Não vendemos fiado'." },
    { titulo: "ROUPAS DOADAS", corpo: "${nome} foi visto na fila da campanha do agasalho, mas era verão. Ele precisava de qualquer coisa para vestir." },
    { titulo: "LIXO DE UM...", corpo: "${nome} achou uma cadeira quebrada no lixo e levou para casa. 'É vintage rústico', defendeu-se." },
    { titulo: "SEM TETO SOLAR", corpo: "O carro de ${nome} não tem teto solar, na verdade não tem nem teto. É um conversível forçado pela ferrugem." },
    { titulo: "PAPELÃO CONFORTÁVEL", corpo: "${nome} avaliou as caixas de papelão da cidade no Google Maps. 'A da TV 50 polegadas é a mais espaçosa'." },
    { titulo: "AMIGO DA ONÇA", corpo: "${nome} visita os amigos bem na hora do jantar. 'Que coincidência, vocês estão comendo?', diz ele." },
    { titulo: "PLANO B", corpo: "${nome} está pensando em virar estátua viva no centro. 'Pelo menos ganho uns trocados e não gasto energia'." },
    { titulo: "IMPOSTO DE RENDA", corpo: "${nome} é o único que não precisa declarar imposto. A Receita Federal mandou uma carta de condolências." },
    { titulo: "SAPATO FURADO", corpo: "${nome} diz que o furo no sapato é 'ventilação estratégica' para os dias quentes." },
    { titulo: "ESPERANÇA", corpo: "${nome} achou uma moeda de 1 real e comemorou como se tivesse ganhado na loteria. O fundo do poço tem mola!" }
  ],

  // 3. O PRESIDIÁRIO (Jailbird)
  PRESIDIARIO: [
    { titulo: "REI DA CELA", corpo: "${nome} já tem cartão fidelidade na cadeia. O diretor do presídio estuda cobrar aluguel dele pela estadia." },
    { titulo: "SOL A QUADRADOS", corpo: "Enquanto todos negociam milhões, ${nome} negocia cigarros na cadeia. Uma pausa forçada nos negócios." },
    { titulo: "VISITA ÍNTIMA?", corpo: "${nome} pediu para receber o tabuleiro na cela. O delegado negou e mandou ele jogar paciência sozinho." },
    { titulo: "HABEAS CORPUS", corpo: "O advogado de ${nome} nem apareceu. 'Ele gosta da comida da prisão', alegou a defesa para a imprensa." },
    { titulo: "FUGA FRUSTRADA", corpo: "${nome} tentou cavar um túnel com uma colher de plástico, mas só achou um cano de esgoto. A pena aumentou." },
    { titulo: "BANHO DE SOL", corpo: "${nome} está aproveitando para se bronzear no pátio. Diz que está em um 'retiro espiritual forçado'." },
    { titulo: "CHEFE DA QUADRILHA", corpo: "${nome} já organizou um campeonato de truco na cela 4. Ele está ganhando todos os maços de cigarro." },
    { titulo: "REBELIÃO?", corpo: "${nome} iniciou um motim porque serviram feijão por cima do arroz. A gastronomia prisional é coisa séria." },
    { titulo: "TATUAGEM NOVA", corpo: "${nome} fez uma tatuagem de 'Amor de Mãe' nas costas usando tinta de caneta. Ficou parecendo 'Amor de Múmia'." },
    { titulo: "SAUDADE DE CASA", corpo: "${nome} chora toda noite abraçado ao travesseiro. Diz que sente falta de pagar aluguel e taxas." },
    { titulo: "BOM COMPORTAMENTO", corpo: "${nome} está lavando a roupa dos outros presos para tentar reduzir a pena. O serviço é impecável." },
    { titulo: "LIVRO NA CADEIA", corpo: "${nome} começou a escrever suas memórias: 'Minha vida atrás das grades: Um erro de dados'." },
    { titulo: "CONTRABANDO", corpo: "${nome} foi pego tentando contrabandear um dado viciado para dentro da cela. A jogatina não para." },
    { titulo: "ALVARÁ DE SOLTURA", corpo: "O juiz perdeu o processo de ${nome}. Ele vai ficar mofando lá até encontrarem a papelada." },
    { titulo: "COLEGA DE CELA", corpo: "${nome} reclama que seu companheiro de cela ronca muito. Pediu transferência para a solitária." },
    { titulo: "MESTRE CUCA", corpo: "${nome} inventou uma receita de 'bóia' gourmet usando restos do almoço. Virou o chef da prisão." },
    { titulo: "INFLUENCER PRESO", corpo: "${nome} está gravando vídeos de 'Rotina na Prisão' para o TikTok com um celular escondido." },
    { titulo: "CARTAS MARCADAS", corpo: "${nome} ganhou o respeito dos guardas ensinando como sonegar imposto no Banco Imobiliário." },
    { titulo: "SERVIÇO COMUNITÁRIO", corpo: "${nome} se ofereceu para pintar as grades em troca de um ventilador na cela. O calor está demais." },
    { titulo: "ARREPENDIDO", corpo: "${nome} jurou que nunca mais vai jogar dados na vida. 'É um jogo do diabo', gritou da janela." },
    { titulo: "AMIZADES PERIGOSAS", corpo: "${nome} ficou amigo do 'Zé Navalha'. Agora ninguém mexe com ele no recreio." },
    { titulo: "CORAL DA PRISÃO", corpo: "${nome} fundou um coral. Eles cantam 'I Want to Break Free' toda manhã. Os guardas odeiam." },
    { titulo: "EXERCÍCIO FÍSICO", corpo: "${nome} está malhando na cadeia. Prometeu sair de lá 'monstrão' para cobrar as dívidas." },
    { titulo: "ADVOGADO PORTA DE CADEIA", corpo: "${nome} contratou um advogado que cobra em coxinha. A defesa não parece promissora." },
    { titulo: "REFLEXÃO", corpo: "${nome} passa os dias olhando para a parede. Diz que está planejando o 'crime perfeito' para a próxima rodada." },
    { titulo: "CANTINA CARA", corpo: "${nome} reclama que os preços da cantina da prisão são um roubo. 'Mais caro que aeroporto', diz." },
    { titulo: "TROCA DE FAVORES", corpo: "${nome} trocou sua sobremesa por proteção. O pudim vale mais que ouro lá dentro." },
    { titulo: "NOVELA DA VIDA REAL", corpo: "${nome} viciou em assistir novela com os guardas. Não quer sair antes do último capítulo." },
    { titulo: "SONO TRANQUILO", corpo: "${nome} diz que dorme melhor na prisão do que fora. 'Aqui não tem cobrador batendo na porta', justifica." },
    { titulo: "CONTAGEM REGRESSIVA", corpo: "${nome} risca a parede contando os dias. Já desenhou um calendário maia inteiro e nada de sair." }
  ],

  // 4. O CONSTRUTOR (Builder - muitas casas)
  CONSTRUTOR: [
    { titulo: "CANTEIRO DE OBRAS", corpo: "Não se dorme na cidade! ${nome} constrói casas freneticamente e promete verticalizar o bairro todo." },
    { titulo: "SETOR HOTELEIRO", corpo: "${nome} inaugurou mais um hotel. Turistas reclamam dos preços, mas o monopólio da hospedagem só cresce." },
    { titulo: "FALTA CIMENTO?", corpo: "Fornecedores de material estão ricos graças a ${nome}, que decidiu colocar um imóvel em cada esquina." },
    { titulo: "SKYLINE MUDOU", corpo: "A vista da cidade mudou. Agora só se vê os prédios de ${nome}. O sol nem bate mais no chão." },
    { titulo: "VALORIZAÇÃO", corpo: "Terrenos vizinhos aos de ${nome} valorizaram. 'Onde ele constrói, vira ouro', dizem especuladores." },
    { titulo: "CIDADE NOVA", corpo: "${nome} está construindo tanto que a prefeitura pensa em dar o nome dele para o bairro." },
    { titulo: "OBRAS ATRASADAS", corpo: "Mentira! As obras de ${nome} são a jato. Casas surgem da noite para o dia como cogumelos." },
    { titulo: "ARQUITETO DO ANO", corpo: "${nome} ganhou prêmio de urbanismo por 'densidade demográfica agressiva'. Ele não desperdiça um metro." },
    { titulo: "CORRETOR FELIZ", corpo: "O corretor de ${nome} comprou um iate com as comissões. 'Ele não para de construir', celebra." },
    { titulo: "ALUGUEL NAS NUVENS", corpo: "Com tantas melhorias, o aluguel nas ruas de ${nome} está impagável. Inquilinos fogem ou pagam chorando." },
    { titulo: "VERTICALIZAÇÃO", corpo: "${nome} quer construir o primeiro arranha-céu de 100 andares no bairro residencial. Vizinhos protestam." },
    { titulo: "BETONEIRA NÃO PARA", corpo: "O barulho de betoneira é a trilha sonora das ruas de ${nome}. Progresso ou poluição sonora?" },
    { titulo: "TINTA FRESCA", corpo: "Cuidado ao encostar nas paredes do bairro. ${nome} acabou de pintar tudo de verde dólar." },
    { titulo: "REFORMA TOTAL", corpo: "${nome} derrubou casas velhas para fazer condomínios de luxo. A gentrificação chegou com força." },
    { titulo: "HOTELARIA DE LUXO", corpo: "Os hotéis de ${nome} têm 5 estrelas e torneiras de ouro. Só a diária custa um rim." },
    { titulo: "EXPANSÃO URBANA", corpo: "${nome} pediu autorização para construir no parque municipal. 'O povo precisa de moradia', argumenta." },
    { titulo: "TIJOLO SOBRE TIJOLO", corpo: "${nome} foi visto assentando tijolos pessoalmente. 'Ninguém faz tão bem quanto eu', diz o magnata mão na massa." },
    { titulo: "BAIRRO PLANEJADO", corpo: "Todas as casas de ${nome} são iguais. Críticos chamam de 'monotonia arquitetônica', ele chama de 'padronização eficiente'." },
    { titulo: "DEMOLIÇÃO", corpo: "${nome} comprou a casa do vizinho só para demolir e aumentar o jardim do seu hotel. Poder é isso." },
    { titulo: "VISTA PARA O MAR", corpo: "${nome} promete que seus prédios no centro terão vista para o mar, mesmo a 500km da costa. O marketing é forte." },
    { titulo: "CASA INTELIGENTE", corpo: "As novas casas de ${nome} falam, acendem luz sozinhas e cobram o aluguel automaticamente da conta do hóspede." },
    { titulo: "CONDOMÍNIO FECHADO", corpo: "${nome} cercou o bairro inteiro. Agora só entra quem tem senha ou muito dinheiro." },
    { titulo: "ÁREA VERDE?", corpo: "${nome} pintou o concreto de verde e chamou de 'parque ecológico'. A sustentabilidade mandou lembranças." },
    { titulo: "HABITE-SE", corpo: "${nome} conseguiu o Habite-se da prefeitura em tempo recorde. Boatos de suborno? Jamais, apenas eficiência." },
    { titulo: "INAUGURAÇÃO", corpo: "Festa de inauguração no novo hotel de ${nome}. Champanhe grátis para quem puder pagar a entrada de 5 mil." },
    { titulo: "SEM VAGAS", corpo: "Os hotéis de ${nome} estão lotados até 2030. Quem quiser reservar tem que entrar na fila de espera." },
    { titulo: "PISCINA OLÍMPICA", corpo: "${nome} instalou piscinas olímpicas em casas de 40m². A física não explica, mas o dinheiro sim." },
    { titulo: "RETROESCOVADEIRA", corpo: "${nome} dirige a retroescavadeira aos domingos por diversão. 'Derrubar coisas me relaxa', diz ele." },
    { titulo: "CONCRETO ARMADO", corpo: "${nome} diz que suas casas aguentam furacão, terremoto e cunhado chato. A estrutura é sólida." },
    { titulo: "CIDADE DORMITÓRIO", corpo: "${nome} transformou o bairro numa cidade dormitório. Ninguém sai de casa com medo dos preços dele." }
  ],

  // 5. O MONOPOLISTA (Full Set - cor completa)
  MONOPOLISTA: [
    { titulo: "CARTEL DAS CORES", corpo: "Atenção: ${nome} fechou o monopólio da região! O CADE foi notificado, mas disse que 'faz parte do jogo'." },
    { titulo: "PEDÁGIO URBANO", corpo: "Quem passar pelas ruas de ${nome} vai pagar caro. Ele unificou a cobrança e o bairro agora é dele." },
    { titulo: "REI DO BAIRRO", corpo: "Vizinhos confirmam: ${nome} é dono de tudo ali. 'Ele manda pintar as calçadas da cor que quer', diz morador." },
    { titulo: "ZONA PROIBIDA", corpo: "O GPS já indica rotas alternativas para evitar o bairro de ${nome}. Cair lá é prejuízo certo." },
    { titulo: "DONO DA RUA", corpo: "${nome} colocou uma cancela na entrada do bairro. 'Só passa quem paga', avisa a placa." },
    { titulo: "UNIFICAÇÃO", corpo: "${nome} derrubou os muros entre as casas e fez um mega terreno. O CEP agora é um só: o dele." },
    { titulo: "LIMPEZA ÉTNICA", corpo: "${nome} expulsou os antigos moradores e trocou tudo por inquilinos de alta renda. O bairro mudou de cara." },
    { titulo: "COBRANÇA ÚNICA", corpo: "Cair na primeira ou na última rua de ${nome} dá no mesmo: falência. O combo de aluguel é mortal." },
    { titulo: "IMPÉRIO COR-DE-ROSA", corpo: "(Ou da cor que for) ${nome} pintou o bairro todo da mesma cor. A poluição visual é grande, mas o lucro é maior." },
    { titulo: "CERCO FECHADO", corpo: "Não tem escapatória. ${nome} comprou todas as saídas. Quem entra no bairro, deixa a carteira." },
    { titulo: "SÍNDICO PERPÉTUO", corpo: "${nome} se autodeclarou síndico vitalício do quarteirão. As regras são dele, o lucro é dele." },
    { titulo: "VALORIZADO", corpo: "Só de ${nome} completar a coleção, os imóveis dobraram de preço. O mercado reage ao monopólio." },
    { titulo: "SEM CONCORRÊNCIA", corpo: "${nome} eliminou a concorrência na região. Agora ele cobra o quanto quer e ninguém pode reclamar." },
    { titulo: "PASSE LIVRE? NÃO", corpo: "${nome} revogou o direito de ir e vir gratuito. A calçada agora tem taxímetro." },
    { titulo: "MONOPÓLIO PURO", corpo: "O sonho de todo capitalista: ${nome} atingiu o nirvana financeiro ao dominar o setor completo." },
    { titulo: "BLOQUEIO", corpo: "Jogadores evitam olhar para o lado do tabuleiro onde ${nome} domina. O medo é real." },
    { titulo: "DOMÍNIO TOTAL", corpo: "${nome} não aceita sócios. O bairro é propriedade privada exclusiva e ele tem cães de guarda." },
    { titulo: "TAXA DE VISITAÇÃO", corpo: "${nome} quer cobrar ingresso só para olharem para seus prédios. A ganância não tem fim." },
    { titulo: "BAIRRO MODELO", corpo: "${nome} diz que seu bairro é modelo de gestão. Modelo de como arrancar dinheiro dos outros, dizem críticos." },
    { titulo: "LÍDER DE MERCADO", corpo: "${nome} dita as regras. Se ele aumenta o aluguel, todos sofrem. O Banco Central está preocupado." },
    { titulo: "COMBO MORTAL", corpo: "${nome} preparou uma armadilha. Quem cair na primeira casa, cai nas outras em sequência. É o fim." },
    { titulo: "CARTEL", corpo: "${nome} foi acusado de formação de cartel... com ele mesmo. A justiça arquivou por falta de outros réus." },
    { titulo: "PODER ABSOLUTO", corpo: "${nome} trocou o nome das ruas para 'Rua do ${nome} 1', 'Rua do ${nome} 2'... O ego inflou." },
    { titulo: "ESTRANGULAMENTO", corpo: "${nome} está estrangulando a economia dos adversários. O dinheiro do jogo flui todo para o bolso dele." },
    { titulo: "PROPRIEDADE PLENA", corpo: "${nome} tem a escritura, a posse e a alma do bairro. Nada acontece lá sem a permissão dele." },
    { titulo: "ZONA DE RISCO", corpo: "O mapa de calor do jogo mostra o bairro de ${nome} em vermelho sangue. Perigo extremo de falência." },
    { titulo: "SEM NEGOCIAÇÃO", corpo: "${nome} avisa: 'Não vendo, não troco, não alugo'. O monopólio é inegociável." },
    { titulo: "HEGEMONIA", corpo: "A hegemonia de ${nome} na região é indiscutível. Ele é o rei, o prefeito e o juiz local." },
    { titulo: "OLIGARQUIA DE UM", corpo: "${nome} formou uma oligarquia de uma pessoa só. A democracia financeira morreu naquele quarteirão." },
    { titulo: "FIM DA LINHA", corpo: "Para os adversários, cair no monopólio de ${nome} é o fim da linha. Game over se aproxima." }
  ],

  // 6. O ALAVANCADO (Muitos bens, pouco dinheiro)
  ALAVANCADO: [
    { titulo: "CRISE DE LIQUIDEZ", corpo: "${nome} tem patrimônio de milionário, mas foi visto contando moedas para comprar um café. Risco alto!" },
    { titulo: "GIGANTE DE PAPEL", corpo: "O império de ${nome} é vasto, mas o caixa está vazio. Analistas preveem liquidação se ele cair numa taxa." },
    { titulo: "RICO SEM DINHEIRO", corpo: "${nome} anda com bolsos vazios e pasta cheia de escrituras. 'Dinheiro é vulgar, terra é eterno', diz devendo." },
    { titulo: "VENDE-SE TUDO?", corpo: "O mercado aguarda ansioso. ${nome} pode ter que queimar ativos a qualquer momento para pagar dívidas." },
    { titulo: "CORDA NO PESCOÇO", corpo: "${nome} está com a corda no pescoço. Uma jogada de azar e o castelo de cartas desmorona." },
    { titulo: "ALAVANCAGEM", corpo: "${nome} operou alavancado demais. Investiu tudo e esqueceu de guardar para o pão. O risco é máximo." },
    { titulo: "DÍVIDA IMINENTE", corpo: "Credores rondam ${nome}. Ele tem bens, mas não tem cash. A execução da dívida pode ser fatal." },
    { titulo: "APARÊNCIAS", corpo: "${nome} mantém as aparências de magnata, mas janta macarrão instantâneo escondido. A falência ronda." },
    { titulo: "OFERTA RELÂMPAGO", corpo: "Fiquem atentos! ${nome} pode fazer uma oferta relâmpago de propriedades a qualquer segundo por desespero." },
    { titulo: "SALDO ZERADO", corpo: "${nome} tentou sacar no caixa eletrônico e a máquina riu. 'Saldo insuficiente', mas com muitos imóveis." },
    { titulo: "CAIXA SECO", corpo: "O fluxo de caixa de ${nome} secou. Ele depende da sorte ou de aluguéis urgentes para sobreviver." },
    { titulo: "RISCO SISTÊMICO", corpo: "Se ${nome} quebrar, vai levar o mercado junto? Não, os outros jogadores vão adorar comprar seus bens baratos." },
    { titulo: "EMPRÉSTIMO?", corpo: "${nome} foi visto pedindo dinheiro emprestado para o porteiro. A situação é humilhante para o magnata." },
    { titulo: "SEM RESERVA", corpo: "${nome} ignorou a regra básica de economia: ter reserva de emergência. Agora reza para não cair em aluguel." },
    { titulo: "TUDO OU NADA", corpo: "${nome} apostou tudo. Se passar ileso nas próximas rodadas, fica rico. Se não, adeus jogo." },
    { titulo: "HIPOTECA?", corpo: "${nome} está consultando as regras de hipoteca no manual. Sinal claro de desespero financeiro." },
    { titulo: "VIVENDO PERIGOSAMENTE", corpo: "${nome} gosta de viver no limite. Saldo baixo e patrimônio alto é adrenalina pura (ou burrice)." },
    { titulo: "CHEQUE SEM FUNDO", corpo: "${nome} passou um cheque que vai voltar. Ele espera receber um aluguel antes da compensação." },
    { titulo: "PEDALADA FISCAL", corpo: "${nome} está fazendo malabarismo financeiro para não declarar falência. É uma questão de tempo." },
    { titulo: "BOLHA IMOBILIÁRIA", corpo: "A bolha pessoal de ${nome} vai estourar? Ele comprou demais e agora não tem como manter." },
    { titulo: "SOCORRO!", corpo: "${nome} olha para os outros jogadores com cara de 'comprem algo de mim, por favor'. O orgulho impede o pedido." },
    { titulo: "CALÇA CURTA", corpo: "${nome} foi pego de calça curta. O mercado virou e ele está exposto sem dinheiro em caixa." },
    { titulo: "FALÊNCIA TÉCNICA", corpo: "Tecnicamente, ${nome} já quebrou. Só falta o oficial de justiça (ou o cobrador do jogo) avisar." },
    { titulo: "SEM TROCO", corpo: "${nome} não tem troco para nada. Se alguém pagar aluguel com nota alta, ele tem que dar uma casa de troco." },
    { titulo: "DINHEIRO DE PLÁSTICO", corpo: "${nome} queria que o jogo aceitasse cartão de crédito. O dinheiro físico dele evaporou." },
    { titulo: "MAOS AO ALTO", corpo: "${nome} se sente assaltado a cada taxa que paga. Ele não tem margem para erro." },
    { titulo: "CASTELO DE AREIA", corpo: "O império de ${nome} é um castelo de areia. A maré alta das contas está chegando." },
    { titulo: "OTIMISTA DEMAIS", corpo: "${nome} achou que o dinheiro nunca acabaria. Acabou. Ficaram só as escrituras para contar história." },
    { titulo: "LEILÃO FORÇADO", corpo: "Se ${nome} não conseguir dinheiro rápido, teremos um leilão forçado de seus bens. Abutres já circulam." },
    { titulo: "SUFOCO", corpo: "${nome} está passando sufoco. Cada dado rolado é uma prece para não cair em propriedade alheia." }
  ],

  // 7. O ESPECULADOR (Muito dinheiro, poucos bens)
  ESPECULADOR: [
    { titulo: "COLCHÃO RECHEADO", corpo: "${nome} está sentado em uma pilha de dinheiro e se recusa a investir. O mercado implora: 'Compre algo!'." },
    { titulo: "DINHEIRO PARADO", corpo: "A inflação vai comer o dinheiro de ${nome}! Ele acumula capital mas ignora os leilões. Estratégia ou medo?" },
    { titulo: "AVAREZA?", corpo: "Enquanto todos constroem, ${nome} apenas observa com a conta gorda. Especialistas questionam se ele sabe jogar." },
    { titulo: "POUPANÇA", corpo: "${nome} acha que ganha o jogo quem termina com mais papel moeda. Alguém avise que precisa de imóveis!" },
    { titulo: "MÃO DE VACA", corpo: "${nome} não abre a mão nem para dar tchau. Tem milhões, mas não gasta um centavo em propriedades." },
    { titulo: "LIQUIDEZ EXCESSIVA", corpo: "${nome} sofre de liquidez excessiva. O dinheiro está mofando no bolso enquanto os terrenos acabam." },
    { titulo: "INVESTIDOR TÍMIDO", corpo: "${nome} tem medo de compromisso. Olha os terrenos, paquera, mas não compra. O dinheiro sobra." },
    { titulo: "ESPERANDO O CAOS", corpo: "${nome} diz que está 'esperando a bolha estourar' para comprar barato. O mercado continua subindo." },
    { titulo: "TIO PATINHAS", corpo: "${nome} mergulha no dinheiro, mas não tem onde morar. É o sem-teto mais rico do jogo." },
    { titulo: "SEM ESTRATÉGIA", corpo: "Analistas dizem que ${nome} esqueceu o objetivo do jogo. Acumular papel não gera aluguel." },
    { titulo: "OPORTUNISTA", corpo: "${nome} está com o caixa cheio esperando alguém quebrar para comprar tudo a preço de banana. Cruel." },
    { titulo: "MEDO DE GASTAR", corpo: "${nome} sua frio só de pensar em gastar. A terapia financeira é recomendada." },
    { titulo: "COFRE CHEIO", corpo: "O cofre de ${nome} não fecha mais. Enquanto isso, seu portfólio imobiliário cabe num post-it." },
    { titulo: "INFLAÇÃO", corpo: "${nome}, cuidado! Dinheiro parado perde valor. Compre tijolo, tijolo é moeda forte!" },
    { titulo: "VISÃO DE LONGO PRAZO?", corpo: "Talvez ${nome} seja um gênio incompreendido... ou apenas alguém que não sabe as regras." },
    { titulo: "BANQUEIRO", corpo: "${nome} tem tanto dinheiro que poderia abrir seu próprio banco e emprestar a juros para os outros." },
    { titulo: "SEM RENDA", corpo: "${nome} tem estoque, mas não tem fluxo. Sem aluguéis, o dinheiro só sai (mesmo que devagar)." },
    { titulo: "CONTADOR DE CÉDULAS", corpo: "${nome} passa o turno contando dinheiro em vez de negociar. O fetichismo monetário é real." },
    { titulo: "TURISTA RICO", corpo: "${nome} viaja pelo tabuleiro com os bolsos cheios, pagando aluguéis sem reclamar, mas sem receber nada." },
    { titulo: "DOADOR UNIVERSAL", corpo: "No fim, ${nome} será apenas o financiador dos outros jogadores, pagando aluguéis caros com sua fortuna." },
    { titulo: "ACOMODADO", corpo: "${nome} está confortável demais. Precisa de um choque de gestão para começar a investir." },
    { titulo: "DESPERDÍCIO", corpo: "Tanto capital na mão de ${nome} é um desperdício. O mercado clama por circulação de riqueza." },
    { titulo: "RETRAÇÃO", corpo: "${nome} causou uma retração econômica ao tirar tanto dinheiro de circulação e guardar no bolso." },
    { titulo: "PERFIL CONSERVADOR", corpo: "O perfil de investidor de ${nome} é 'Conservador Nível Avó'. Poupança e colchão." },
    { titulo: "MEDO DO RISCO", corpo: "${nome} tem aversão ao risco. Imóveis podem desvalorizar? Ele prefere o papel pintado." },
    { titulo: "FUTURO INCERTO", corpo: "Se ${nome} não comprar logo, vai ser engolido pelos magnatas imobiliários nas próximas rodadas." },
    { titulo: "MÃO FECHADA", corpo: "${nome} usa cola na mão para o dinheiro não sair. É difícil fazer negócios com ele." },
    { titulo: "ESTOQUE DE PAPEL", corpo: "${nome} está estocando papel moeda como se fosse papel higiênico na pandemia. Exagero." },
    { titulo: "DRAGÃO", corpo: "${nome} senta sobre seu tesouro e dorme. Nenhuma aventura, nenhum investimento, só sono e ouro." },
    { titulo: "ACORDA!", corpo: "Alguém dê um café para ${nome}! O jogo está acontecendo e ele está apenas acumulando." }
  ],

  // 8. O SEM TETO (0 propriedades rodada avançada)
  SEM_TETO: [
    { titulo: "MORADOR DE RUA?", corpo: "${nome} ainda não comprou nada! Ele vive de favor passando pelas casas dos outros e dormindo na praça." },
    { titulo: "NÔMADE DIGITAL", corpo: "${nome} diz que 'bens materiais prendem'. Na verdade, ele só perdeu todas as oportunidades de compra." },
    { titulo: "AZAR NO DADO", corpo: "${nome} diz que o dado está viciado. Ele só cai em propriedades que já têm dono. A vida é dura." },
    { titulo: "FALTA DE OPORTUNIDADE", corpo: "${nome} alega que o mercado está saturado. 'Não sobrou nada pra mim', chora ele." },
    { titulo: "VIVENDO DE FAVOR", corpo: "${nome} sobrevive graças à caridade alheia (e sorte nos dados). Não tem onde cair morto." },
    { titulo: "SEM ENDEREÇO", corpo: "${nome} não tem comprovante de residência. O banco vai fechar a conta dele por falta de endereço." },
    { titulo: "TURISTA ETERNO", corpo: "${nome} passeia pelo tabuleiro como um turista. Não cria raízes, não constrói nada. Apenas passa." },
    { titulo: "INVISÍVEL", corpo: "${nome} é um fantasma no mercado imobiliário. Ninguém nota sua presença, exceto quando ele paga aluguel." },
    { titulo: "ZERO BENS", corpo: "A declaração de bens de ${nome} cabe num post-it: 'Nada'. O Leão da Receita nem perde tempo." },
    { titulo: "DESAPEGADO", corpo: "${nome} pratica o desapego material extremo. Tão extremo que ele não tem nada no jogo." },
    { titulo: "HÓSPEDE PROFISSIONAL", corpo: "${nome} conhece todos os hotéis dos adversários. É o cliente VIP que financia a riqueza alheia." },
    { titulo: "SEM TETO, SEM LEI", corpo: "${nome} ameaça invadir o parque público se não conseguir comprar uma casa logo." },
    { titulo: "CORRIDA CONTRA O TEMPO", corpo: "As propriedades estão acabando e ${nome} continua zerado. O pânico começa a bater." },
    { titulo: "ESPECTADOR", corpo: "${nome} comprou ingresso para assistir os outros jogarem. Pelo menos é o que parece." },
    { titulo: "MÁ FASE", corpo: "${nome} está numa maré de azar histórica. O universo conspira para que ele continue pobre de bens." },
    { titulo: "SEM RAIZ", corpo: "${nome} é como uma folha ao vento. Vai onde o dado manda, mas nunca finca sua bandeira." },
    { titulo: "PERDIDO", corpo: "${nome} parece perdido no tabuleiro. 'Onde compra casa?', pergunta ele na rodada 50." },
    { titulo: "SONHO DA CASA PRÓPRIA", corpo: "${nome} sonha com a casa própria, mas acorda com o aluguel do vizinho. Pesadelo recorrente." },
    { titulo: "FILA DA COHAB", corpo: "${nome} entrou na fila da habitação popular. O jogo não está fácil pra ninguém." },
    { titulo: "DESABRIGADO", corpo: "A assistência social do jogo foi acionada para cuidar de ${nome}. Ele dorme no tabuleiro." },
    { titulo: "MOCHILEIRO", corpo: "${nome} vive com uma mochila nas costas. Tudo que ele tem cabe ali (que é basicamente nada)." },
    { titulo: "EXCLUÍDO", corpo: "Os outros jogadores fazem reuniões de condomínio e ${nome} fica de fora. Ele não é proprietário." },
    { titulo: "LIVRE E LEVE", corpo: "${nome} diz que se sente leve sem a responsabilidade de administrar imóveis. É uma forma de ver..." },
    { titulo: "VAGABUNDO ILUMINADO", corpo: "${nome} atingiu a iluminação espiritual: não ter nada. Mas no Banco Imobiliário isso é perder." },
    { titulo: "SEM HERANÇA", corpo: "${nome} não vai deixar nada para os herdeiros. Apenas histórias de aluguéis pagos." },
    { titulo: "CIDADÃO DE 2ª CLASSE", corpo: "Sem propriedades, ${nome} é tratado como cidadão de segunda classe no tabuleiro." },
    { titulo: "NA MIRA", corpo: "${nome} está na mira da eliminação. Sem renda passiva, o dinheiro só sai. A matemática é cruel." },
    { titulo: "ACAMPAMENTO", corpo: "${nome} montou uma barraca na casa de 'Sorte'. Diz que é o único lugar público que sobrou." },
    { titulo: "PIADA PRONTA", corpo: "Os adversários já fazem piada: '${nome} vai comprar a Prisão pra ter onde morar'." },
    { titulo: "ÚLTIMA CHANCE", corpo: "${nome} precisa comprar algo urgente ou aceitar a derrota. O tempo está acabando." }
  ],

  // 9. O COLECIONADOR (Maior qtd de propriedades)
  COLECIONADOR: [
    { titulo: "DONO DA CIDADE", corpo: "${nome} precisou alugar um galpão só para guardar suas escrituras. Ele quer comprar o tabuleiro todo!" },
    { titulo: "FALTA ESPAÇO", corpo: "O chaveiro da cidade diz que ${nome} tem a cópia da chave de metade das casas do município. É um exagero." },
    { titulo: "COMPRADOR COMPULSIVO", corpo: "${nome} não pode ver uma placa de 'Vende-se'. Ele compra até terreno no pântano." },
    { titulo: "MAPA DO TESOURO", corpo: "O mapa do jogo está pintado com as cores de ${nome}. Ele está em toda parte, onipresente." },
    { titulo: "PORTFÓLIO GIGANTE", corpo: "O portfólio de ${nome} é mais grosso que a lista telefônica. Ele nem lembra o que tem." },
    { titulo: "ADMINISTRADORA", corpo: "${nome} abriu sua própria imobiliária para gerenciar tantos bens. O trabalho é grande, o lucro também." },
    { titulo: "MONOPÓLIO PESSOAL", corpo: "${nome} não busca qualidade, busca quantidade. Ele quer dominar pelo volume." },
    { titulo: "EXPANSÃO TERRITORIAL", corpo: "${nome} age como um imperador conquistando territórios. Nada escapa de sua ganância." },
    { titulo: "SENHOR DAS TERRAS", corpo: "${nome} exige ser chamado de 'Senhor das Terras'. O ego cresceu junto com o patrimônio." },
    { titulo: "IPTU RECORD", corpo: "O carnê de IPTU de ${nome} vem em um caminhão. É o maior contribuinte da cidade." },
    { titulo: "ESCRITURAS", corpo: "${nome} usa escrituras como leque nos dias quentes. Tem papel sobrando." },
    { titulo: "REI DO BANCO IMOBILIÁRIO", corpo: "${nome} entendeu o jogo: comprar tudo. Seus adversários estão ficando sem chão." },
    { titulo: "SEM VIZINHOS", corpo: "${nome} não tem vizinhos, porque ele comprou a casa deles também. Vive cercado por si mesmo." },
    { titulo: "JOGO DE WAR?", corpo: "${nome} acha que está jogando War e quer pintar o mapa da sua cor. A estratégia está funcionando." },
    { titulo: "FOME DE TERRA", corpo: "${nome} tem uma fome insaciável por terra. Ele compraria a casa da própria mãe se estivesse no tabuleiro." },
    { titulo: "INVESTIDOR NATO", corpo: "${nome} diversifica: tem casa no morro, na praia e no centro. Risco diluído, lucro garantido." },
    { titulo: "MINHA CASA, MINHA VIDA", corpo: "${nome} privatizou o programa de habitação. Agora é 'Minha Casa, Propriedade do ${nome}'." },
    { titulo: "LOTEAMENTO", corpo: "${nome} está loteando até as áreas verdes. Onde tem espaço, ele mete uma escritura." },
    { titulo: "SEM SAÍDA", corpo: "Para onde você correr, cai numa casa de ${nome}. O cerco está se fechando." },
    { titulo: "LATIFUNDIÁRIO", corpo: "${nome} é o maior latifundiário urbano da história. A reforma agrária passou longe daqui." },
    { titulo: "DONO DO CEP", corpo: "${nome} é dono de tantos CEPs que os correios entregam a correspondência direto na mão dele." },
    { titulo: "COLEÇÃO COMPLETA", corpo: "${nome} quer completar o álbum de figurinhas do tabuleiro. Faltam poucas para ele ter tudo." },
    { titulo: "VISÃO DE ÁGUIA", corpo: "${nome} vê oportunidade onde outros veem terreno baldio. Ele compra, espera e lucra." },
    { titulo: "MARECHAL DE CAMPO", corpo: "${nome} move seus peões como um general. Cada compra é uma vitória tática." },
    { titulo: "ARQUIVO MORTO", corpo: "${nome} tem propriedades que nem visita. Comprou só para os outros não terem." },
    { titulo: "GORDURA PARA QUEIMAR", corpo: "${nome} tem tanta propriedade que pode vender metade e ainda ser rico. Situação confortável." },
    { titulo: "POLÍTICA DE BOA VIZINHANÇA", corpo: "${nome} não precisa de boa vizinhança, ele é o dono da vizinhança. Ele faz as regras." },
    { titulo: "TUDO MEU", corpo: "${nome} canta 'Tudo o que você vê é meu'. E ele não está mentindo." },
    { titulo: "SOBERANO", corpo: "${nome} caminha pelo tabuleiro inspecionando seus domínios. Os súditos (outros jogadores) pagam tributo." },
    { titulo: "FIM DO JOGO?", corpo: "Com tantas propriedades, ${nome} já está encomendando a faixa de campeão. Será que alguém impede?" }
  ],

  // 10. BARÃO DOS TRANSPORTES (Dono de Aeroportos/Estações)
  BARAO_AEREO: [
    { titulo: "MALHA AÉREA", corpo: "${nome} domina os céus. Quem precisar viajar vai ter que pagar a taxa de embarque dele. O monopólio voa alto." },
    { titulo: "MONOPÓLIO DO IR E VIR", corpo: "Trens, aviões e ônibus. ${nome} controla o transporte e as passagens acabaram de aumentar." },
    { titulo: "REI DOS TRILHOS", corpo: "${nome} comprou todas as estações. O transporte público agora é privado e caro." },
    { titulo: "AEROPORTO PARTICULAR", corpo: "${nome} transformou o aeroporto em sua sala de estar. Só decola quem paga o pedágio." },
    { titulo: "TARIFAÇO", corpo: "${nome} anunciou aumento nas tarifas. 'Manutenção da via', alegou enquanto contava dinheiro." },
    { titulo: "LOGÍSTICA", corpo: "${nome} é o magnata da logística. Nada se move no tabuleiro sem o consentimento (e o boleto) dele." },
    { titulo: "SEM ESCAPATÓRIA", corpo: "Tentou fugir de carro? ${nome} é dono da estrada. Tentou avião? Ele é dono do aeroporto." },
    { titulo: "PASSAGEM CARA", corpo: "Viajar no tabuleiro ficou proibitivo. ${nome} cobra preço de classe executiva por assento econômico." },
    { titulo: "HUB DE CONEXÃO", corpo: "Todas as rotas levam a ${nome}. Ele transformou suas estações em hubs de lucro." },
    { titulo: "ATRITO ZERO", corpo: "${nome} diz que seus trens têm atrito zero, mas o preço tem atrito máximo com o bolso dos passageiros." },
    { titulo: "CLASSE A", corpo: "${nome} só viaja de primeira classe nas próprias companhias. Os outros viajam no bagageiro." },
    { titulo: "OVERBOOKING", corpo: "${nome} pratica overbooking de aluguéis. Cobra de dois jogadores ao mesmo tempo se puder." },
    { titulo: "MILHAS AÉREAS", corpo: "${nome} criou um programa de milhas. A cada 10 aluguéis pagos, você ganha um 'obrigado'." },
    { titulo: "GREVE? JAMAIS", corpo: "No império de transporte de ${nome} não tem greve, só lucro. Os trens rodam na hora certa (a hora de pagar)." },
    { titulo: "INFRAESTRUTURA", corpo: "${nome} investiu pesado em infraestrutura... para cobrar mais caro depois. O velho truque." },
    { titulo: "MAGNATA DO VAPOR", corpo: "${nome} parece um barão do século XIX. Só falta a cartola e o monóculo enquanto cobra os tickets." },
    { titulo: "TRANSIT BOARD", corpo: "${nome} senta no conselho de transportes e aprova os próprios aumentos. Conflito de interesses?" },
    { titulo: "SEM CARONA", corpo: "${nome} proibiu caronas. Todo mundo tem que pagar a passagem cheia. A amizade acaba na catraca." },
    { titulo: "VIGILÂNCIA", corpo: "${nome} instalou câmeras nas estações para garantir que ninguém pule a roleta sem pagar." },
    { titulo: "VIAJE COMIGO", corpo: "O slogan de ${nome} é 'Viaje comigo e deixe seu dinheiro aqui'. Honesto e direto." },
    { titulo: "TURBULÊNCIA", corpo: "${nome} avisa: previsão de turbulência financeira para quem pousar em seus aeroportos." },
    { titulo: "CHECK-IN", corpo: "Faça o check-in e prepare o check-out da sua conta bancária. ${nome} está te esperando." },
    { titulo: "PONTE AÉREA", corpo: "${nome} é dono da ponte aérea mais cara do mundo. O cafézinho a bordo custa 50 reais." },
    { titulo: "MAQUINISTA RICO", corpo: "${nome} é o maquinista e o dono do trem. Ele apita na hora de cobrar." },
    { titulo: "RODOVIÁRIA", corpo: "Até a rodoviária é de ${nome}. Ele cobra taxa de uso do banheiro e taxa de assento." },
    { titulo: "SEM FRONTEIRAS", corpo: "${nome} não acredita em fronteiras, apenas em zonas de cobrança. O mundo é um grande pedágio." },
    { titulo: "GLOBALIZAÇÃO", corpo: "${nome} globalizou a cobrança. Em qualquer estação, a moeda é a mesma: o seu dinheiro." },
    { titulo: "JET SET", corpo: "${nome} vive no Jet Set, voando de taxa em taxa, acumulando milhas de riqueza." },
    { titulo: "TAXA DE EMBARQUE", corpo: "A taxa de embarque de ${nome} subiu 200%. Motivo: 'Porque eu quis'." },
    { titulo: "FIM DA LINHA", corpo: "A próxima estação é: Falência. Por favor, desembarquem pela direita e paguem a ${nome}." }
  ],

  // 11. REI DA SUCATA (Dono das propriedades baratas - Marrom/Azul Claro)
  REI_DA_SUCATA: [
    { titulo: "GENTRIFICAÇÃO", corpo: "${nome} está comprando todos os bairros populares. Moradores temem que o aluguel do cortiço suba de preço." },
    { titulo: "LUCRO NO GIRO", corpo: "Enquanto outros buscam luxo, ${nome} aposta na quantidade e domina a periferia. De grão em grão..." },
    { titulo: "FAVELA CHIC", corpo: "${nome} gourmetizou a favela. Agora chama 'comunidade vertical' e cobra caro pelo 'conceito'." },
    { titulo: "BARÃO DO BARRACO", corpo: "${nome} é o dono de todos os barracos da zona sul. O acabamento é ruim, mas o aluguel é garantido." },
    { titulo: "MINHA CASA MINHA DÍVIDA", corpo: "${nome} financia casas populares com juros de agiota. O povo paga porque precisa." },
    { titulo: "ALUGUEL SOCIAL?", corpo: "Não com ${nome}. Ele cobra preço de mercado até no barraco de madeira. O capitalismo é selvagem." },
    { titulo: "REFORMA MEIA-BOCA", corpo: "${nome} passou uma mão de cal na parede e triplicou o aluguel. 'Estilo rústico', diz ele." },
    { titulo: "CORTIÇO DO MILHÃO", corpo: "${nome} fatura milhões com aluguéis baratos. A rotatividade é alta, mas a vacância é zero." },
    { titulo: "PERIFERIA NO TOPO", corpo: "${nome} prova que a periferia dá lucro. Ele é o rei da quebrada (imobiliária)." },
    { titulo: "PUXADINHO", corpo: "${nome} legalizou o puxadinho e está cobrando aluguel extra pela 'área expandida'." },
    { titulo: "DONO DA LAJE", corpo: "${nome} aluga a laje para festas e bronzeamento. Cada metro quadrado é monetizado." },
    { titulo: "POPULAR E CARO", corpo: "${nome} diz que seus imóveis são populares, mas o preço é impopular. A demanda é alta." },
    { titulo: "MERCADO DE MASSA", corpo: "${nome} ganha no volume. Cobra pouco de muitos e enche o bolso no final do dia." },
    { titulo: "SEM MANUTENÇÃO", corpo: "Inquilinos reclamam de goteiras, mas ${nome} diz que é 'feature de teto solar natural'." },
    { titulo: "BAIXO CUSTO", corpo: "A estratégia de ${nome} é baixo custo, alta rentabilidade. Ele não gasta com luxo, só com tinta." },
    { titulo: "REI DA QUITINETE", corpo: "${nome} dividiu uma sala em 4 quitinetes. Otimização de espaço nível hard." },
    { titulo: "INVASÃO?", corpo: "${nome} comprou a área invadida e agora cobra aluguel dos ocupantes. Jogada de mestre (ou vilão)." },
    { titulo: "ZONA DE COMÉRCIO", corpo: "${nome} transformou a rua popular em um camelódromo organizado. Ele cobra taxa de banca." },
    { titulo: "BARULHO E LUCRO", corpo: "O bairro de ${nome} é barulhento e caótico, mas o dinheiro entra silenciosamente na conta dele." },
    { titulo: "SEM ELEVADOR", corpo: "Prédios de 5 andares sem elevador. ${nome} diz que cobra taxa de academia inclusa na escada." },
    { titulo: "VISTA PRO MURO", corpo: "${nome} aluga quartos com vista para o muro do vizinho como 'ambiente privativo e introspectivo'." },
    { titulo: "AGLOMERAÇÃO", corpo: "${nome} não se importa com aglomeração, desde que todos paguem aluguel. Quanto mais gente, melhor." },
    { titulo: "ZONA LESTE", corpo: "${nome} é o magnata da Zona Leste (ou equivalente). Ele domina o lado esquecido do mapa." },
    { titulo: "SEM GLAMOUR", corpo: "${nome} não tem glamour, tem dinheiro. Ele deixa o luxo para os outros e fica com o lucro." },
    { titulo: "CHÃO BATIDO", corpo: "${nome} aluga terreno de chão batido como 'estacionamento ecológico'. O marketing é tudo." },
    { titulo: "TETO DE ZINCO", corpo: "Quando chove, ninguém dorme nos imóveis de ${nome}. Mas o aluguel cai na conta faça chuva ou faça sol." },
    { titulo: "MAMBEMBE", corpo: "O império de ${nome} parece mambembe, mas é sólido. Ele construiu sua fortuna no tijolo baiano." },
    { titulo: "SEM GOURMET", corpo: "Aqui não tem varanda gourmet. Tem tanque de lavar roupa e varal compartilhado. ${nome} é prático." },
    { titulo: "VIDA REAL", corpo: "${nome} joga o jogo da vida real: onde a maioria mora e paga conta. Ele é o dono da realidade." },
    { titulo: "SUCATA DE OURO", corpo: "Podem chamar de sucata, mas para ${nome} é ouro. Ele transformou ruínas em renda." }
  ],

  // 12. A ELITE (Dono das propriedades caras - Verde/Azul Escuro)
  ELITE: [
    { titulo: "ALTA SOCIEDADE", corpo: "${nome} só investe em bairro nobre. Se você não estiver vestindo terno, nem passe pela calçada dele." },
    { titulo: "IPTU MAIS CARO", corpo: "As propriedades de ${nome} valem ouro. Cair lá é falência certa para os desavisados. Prepare o bolso." },
    { titulo: "ARISTOCRACIA", corpo: "${nome} age como um lorde inglês. Só compra o que há de melhor e olha com desprezo para as propriedades marrons." },
    { titulo: "BAIRRO NOBRE", corpo: "No bairro de ${nome}, até o lixo é recolhido por mordomos. O aluguel reflete esse nível de serviço." },
    { titulo: "EXCLUSIVE", corpo: "${nome} lançou um condomínio 'Exclusive'. Só entra quem tem sobrenome composto ou conta na Suíça." },
    { titulo: "JARDINS", corpo: "${nome} é o dono dos Jardins. As árvores são aparadas com tesoura de ouro e a grama é importada." },
    { titulo: "SEM POBREZA", corpo: "${nome} instalou um campo de força anti-pobreza em seus domínios. A taxa de entrada é altíssima." },
    { titulo: "LUXO SUPREMO", corpo: "Torneiras de diamante e chão de mármore carrara. Os imóveis de ${nome} são um exagero de bom gosto." },
    { titulo: "GOLFE CLUBE", corpo: "${nome} construiu um campo de golfe no meio da cidade. Ocupa o espaço de 50 casas populares, mas é chique." },
    { titulo: "HELIPONTO", corpo: "Todas as casas de ${nome} têm heliponto. Ele não espera no trânsito e cobra caro por isso." },
    { titulo: "SEGURANÇA VIP", corpo: "O bairro de ${nome} tem mais câmeras que o Big Brother. A segurança é total, assim como o preço." },
    { titulo: "VISINHOS FAMOSOS", corpo: "${nome} diz que seus inquilinos são celebridades. Cobra ágio pela 'vibe' do lugar." },
    { titulo: "AR PURO", corpo: "${nome} engarrafou o ar puro de suas propriedades e vende como souvenir. O capitalismo respira." },
    { titulo: "OURO AZUL", corpo: "${nome} é dono das propriedades azuis, as mais cobiçadas. Ele tem a jóia da coroa do tabuleiro." },
    { titulo: "FIM DE JOGO", corpo: "Cair no hotel de ${nome} na zona nobre é game over instantâneo. É a armadilha de luxo perfeita." },
    { titulo: "CHAMPANHE", corpo: "${nome} celebra cada aluguel recebido estourando uma Chandon. A vida é boa no topo." },
    { titulo: "ELEVADOR PRIVATIVO", corpo: "Nos prédios de ${nome}, o carro sobe de elevador até a sala. Ostentação nível máximo." },
    { titulo: "SEM DESCONTO", corpo: "${nome} não dá desconto. 'Qualidade tem preço', diz ele com nariz empinado." },
    { titulo: "BOUTIQUE", corpo: "${nome} transformou o comércio local em ruas de boutiques de grife. Nada de padaria, só boulangerie." },
    { titulo: "VERNISSAGE", corpo: "${nome} organiza vernissages em seus imóveis vagos. Arte e especulação imobiliária de mãos dadas." },
    { titulo: "ALTO PADRÃO", corpo: "O padrão de acabamento de ${nome} é ISO 9000 de luxo. Não há defeitos, apenas cifras." },
    { titulo: "STATUS", corpo: "Pagar aluguel para ${nome} dá status. Você fica pobre, mas fica pobre com estilo." },
    { titulo: "CAVIAR", corpo: "${nome} serve caviar nas reuniões de condomínio. A taxa de condomínio custa mais que o aluguel dos outros." },
    { titulo: "MÁRMORE", corpo: "${nome} revestiu a calçada de mármore. Escorrega quando chove, mas é lindo e caro." },
    { titulo: "CAPITALISTA SELVAGEM", corpo: "${nome} representa o topo da pirâmide alimentar do jogo. Ele come os pequenos no café da manhã." },
    { titulo: "SEM MISTURA", corpo: "${nome} não mistura seus imóveis com o resto. Ele criou uma ilha de prosperidade no meio do caos." },
    { titulo: "VISTA PANORÂMICA", corpo: "Dos seus arranha-céus, ${nome} vê a pobreza dos outros jogadores lá embaixo. A vista é impagável." },
    { titulo: "CLUBE DO WHISKY", corpo: "${nome} fechou negócios bebendo whisky 18 anos. O nível do jogo dele é outro." },
    { titulo: "PÉROLA", corpo: "${nome} tem a pérola do tabuleiro. Todos cobiçam, mas só ele tem o cacife para manter." },
    { titulo: "ELITE BRANCA", corpo: "As casas de ${nome} são todas brancas e minimalistas. Sujeira não é permitida, nem atraso no pagamento." }
  ],

  // 13. O TURISTA (Está em 'Visitante' ou 'Estacionamento')
  TURISTA: [
    { titulo: "SÓ OBSERVANDO", corpo: "${nome} tirou o dia para passear. Foi visto no Estacionamento Grátis comendo pipoca enquanto o mercado pega fogo." },
    { titulo: "VISITA DE CORTESIA", corpo: "${nome} está apenas visitando a prisão. 'O ambiente é seguro e o aluguel é zero', comentou aliviado." },
    { titulo: "FÉRIAS", corpo: "${nome} decidiu tirar férias do capitalismo. Está parado na casa neutra vendo a vida passar." },
    { titulo: "ZONA NEUTRA", corpo: "${nome} buscou refúgio na Suíça do tabuleiro (Estacionamento). Lá, as dívidas não o alcançam." },
    { titulo: "DESCANSO", corpo: "Enquanto todos correm, ${nome} descansa. Ele descobriu que não jogar às vezes é a melhor jogada." },
    { titulo: "PIQUENIQUE", corpo: "${nome} estendeu uma toalha no Estacionamento Grátis e está fazendo um piquenique. A paz reina." },
    { titulo: "INSPEÇÃO", corpo: "${nome} foi inspecionar as celas, mas do lado de fora. 'Só verificando a concorrência', disse." },
    { titulo: "MEDO DE JOGAR", corpo: "${nome} está escondido na zona segura. Ele tem medo de lançar os dados e cair em desgraça." },
    { titulo: "CAFÉ COM O GUARDA", corpo: "${nome} levou donuts para os guardas da prisão. Está fazendo networking caso precise ser preso no futuro." },
    { titulo: "TURISMO CARCERÁRIO", corpo: "${nome} acha a arquitetura da prisão fascinante. Está tirando selfies na grade (pelo lado de fora)." },
    { titulo: "PONTO DE ENCONTRO", corpo: "${nome} marcou com os amigos no Estacionamento. É o único lugar onde não se paga para ficar em pé." },
    { titulo: "ESCAPOU", corpo: "${nome} suspirou aliviado ao cair no Estacionamento. Ele escapou por pouco de um aluguel milionário na casa ao lado." },
    { titulo: "OASIS", corpo: "O Estacionamento é um oásis no deserto de cobranças. ${nome} está bebendo água de coco lá." },
    { titulo: "SEM MULTA", corpo: "${nome} estacionou em vaga proibida, mas como é 'Estacionamento Grátis', ninguém pode multar. A vida é bela." },
    { titulo: "OBSERVADOR DA ONU", corpo: "${nome} atua como observador da ONU na zona de conflito. Ele monitora as falências alheias de longe." },
    { titulo: "ZEN", corpo: "${nome} está meditando na casa neutra. 'O dinheiro é ilusão, a paz é real', diz o guru momentâneo." },
    { titulo: "SAFE ZONE", corpo: "${nome} encontrou o 'save point' do jogo. Pena que ele tem que sair na próxima rodada." },
    { titulo: "REFÚGIO", corpo: "Fugindo de credores, ${nome} se escondeu atrás da guarita do estacionamento. Estratégia de sobrevivência." },
    { titulo: "CAMELÔ", corpo: "${nome} aproveitou o movimento do Estacionamento para vender água mineral. O empreendedorismo não para." },
    { titulo: "PAUSA PARA O LANCHE", corpo: "${nome} pediu pizza no Estacionamento. O motoboy achou fácil porque não tem portaria." },
    { titulo: "CALMARIA", corpo: "A calmaria antes da tempestade. ${nome} aproveita o silêncio antes de voltar para a selva de pedra." },
    { titulo: "VISITA GUIADA", corpo: "${nome} está guiando um tour pela prisão. 'Aqui vemos onde os falidos choram', explica aos turistas." },
    { titulo: "LIVRE", corpo: "${nome} sorri para os presos. 'Eu sou livre', ele grita, provocando quem está atrás das grades." },
    { titulo: "ESTACIONAMENTO VIP", corpo: "${nome} estacionou seu carro imaginário na vaga de deficiente moral. O guarda apenas observou." },
    { titulo: "PONTO CEGO", corpo: "${nome} achou um ponto cego no tabuleiro onde as taxas não o veem. Ele quer morar ali." },
    { titulo: "SONECA", corpo: "${nome} tirou um cochilo no banco da praça (Visitante). Acordou renovado para gastar dinheiro." },
    { titulo: "SEM TICKET", corpo: "${nome} validou o ticket do estacionamento e ganhou isenção. Pequenas vitórias do dia a dia." },
    { titulo: "HIDRATAÇÃO", corpo: "${nome} parou para beber água. O jogo é longo e a desidratação financeira é um risco." },
    { titulo: "ESTRATÉGIA DEFENSIVA", corpo: "Técnicos dizem que cair no Estacionamento é uma jogada defensiva brilhante de ${nome}. Ou pura sorte." },
    { titulo: "RECARREGANDO", corpo: "${nome} está recarregando as energias (e a sorte) para a próxima volta no tabuleiro." }
  ],

  // 14. O SORTUDO (Está na casa 'Sorte')
  SORTUDO: [
    { titulo: "DIA DE SORTE?", corpo: "${nome} parou na casa da Sorte. O destino do jogo pode mudar com a próxima carta que ele tirar." },
    { titulo: "TESTANDO O DESTINO", corpo: "Todos olham para ${nome}. Ele está prestes a desafiar a probabilidade na casa de Sorte." },
    { titulo: "ROLETA RUSSA", corpo: "${nome} vai tirar uma carta. Pode ser um milhão ou a prisão. A tensão é palpável." },
    { titulo: "MÃO SANTA", corpo: "${nome} diz que tem a mão santa para cartas. Vamos ver se o baralho concorda." },
    { titulo: "TREVO DE 4 FOLHAS", corpo: "${nome} carrega um trevo no bolso. Ele confia na sorte mais do que na estratégia." },
    { titulo: "CORAÇÃO NA BOCA", corpo: "${nome} suou frio ao cair na Sorte. Da última vez, ele foi taxado. O trauma é recente." },
    { titulo: "VAI OU RACHA", corpo: "É tudo ou nada para ${nome}. Uma carta boa o salva, uma ruim o afunda. O drama está armado." },
    { titulo: "CARTOMANTE", corpo: "${nome} consultou uma cartomante antes do jogo. Ela disse para evitar cartas amarelas. Veremos." },
    { titulo: "SUSPENSE", corpo: "A música de suspense toca. ${nome} estende a mão para o monte de cartas. O que virá?" },
    { titulo: "SORRISO NERVOSO", corpo: "${nome} sorri, mas está nervoso. A casa de Sorte/Revés é a verdadeira vilã do jogo." },
    { titulo: "DEDOS CRUZADOS", corpo: "${nome} cruzou os dedos das mãos e dos pés. Ele precisa muito de dinheiro agora." },
    { titulo: "DESTINO INCERTO", corpo: "O futuro de ${nome} está escrito num pedaço de papel virtual. A sorte está lançada." },
    { titulo: "ROLETA DA VIDA", corpo: "A vida é uma caixinha de surpresas e ${nome} acabou de abrir a tampa." },
    { titulo: "FÉ NO BARALHO", corpo: "${nome} reza para todos os santos do capitalismo. Ele quer um bônus, não uma multa." },
    { titulo: "AUDÁCIA", corpo: "${nome} caiu na Sorte de propósito? Parece que ele gosta de viver perigosamente." },
    { titulo: "SURPRESINHA", corpo: "O jogo preparou uma surpresinha para ${nome}. Pode ser um presente ou uma bomba." },
    { titulo: "LOTERIA", corpo: "${nome} encara a carta como um bilhete de loteria. A esperança é a última que morre." },
    { titulo: "CAIXA DE PANDORA", corpo: "${nome} vai abrir a Caixa de Pandora. Espero que tenha esperança (e dinheiro) lá dentro." },
    { titulo: "JOGO DE CINTURA", corpo: "Se vier azar, ${nome} vai ter que ter jogo de cintura. Se vier sorte, vai ter festa." },
    { titulo: "MOMENTO DA VERDADE", corpo: "Chegou a hora da verdade para ${nome}. A carta vai definir seu humor pelas próximas rodadas." },
    { titulo: "SORTE NO AMOR?", corpo: "Dizem que quem tem sorte no jogo, tem azar no amor. ${nome} prefere o dinheiro mesmo." },
    { titulo: "VIBRAÇÃO POSITIVA", corpo: "${nome} pede vibração positiva da torcida. Ele vai virar a carta!" },
    { titulo: "SINAL DIVINO", corpo: "${nome} busca um sinal divino nas cartas. O sinal pode ser 'Pague 100 reais'." },
    { titulo: "DESTINO SELADO", corpo: "A carta já foi escolhida pelo algoritmo. O destino de ${nome} já está selado." },
    { titulo: "RISADA DO DESTINO", corpo: "O destino ri da cara de ${nome}. Vamos ver se é uma risada boa ou sádica." },
    { titulo: "CARTA NA MANGA", corpo: "${nome} queria ter uma carta na manga, mas tem que pegar a do monte mesmo." },
    { titulo: "REVÉS?", corpo: "Será Sorte ou Revés? A dualidade da vida se apresenta para ${nome}." },
    { titulo: "FORTUNA", corpo: "A fortuna sorri para os audazes. ${nome} foi audaz ao cair ali." },
    { titulo: "EXPECTATIVA", corpo: "A expectativa é alta. ${nome} precisa de um milagre econômico." },
    { titulo: "CLÍMAX", corpo: "Este é o clímax da rodada. Todos param para ver o que ${nome} vai tirar." }
  ],

  // 15. NORMAL (Fallback)
  NORMAL: [
    { titulo: "DIA TRANQUILO", corpo: "Nada acontece na cidade. O mercado está estável e ${nome} continua andando em círculos." },
    { titulo: "CLIMA ESTÁVEL", corpo: "O mercado segue morno. ${nome} joga os dados e espera o melhor, sem grandes emoções." },
    { titulo: "NOTÍCIA DE ÚLTIMA HORA", corpo: "Não há notícias. ${nome} segue sua rotina de jogar dados e torcer pelo melhor." },
    { titulo: "TRÂNSITO", corpo: "${nome} reclama do trânsito no tabuleiro. 'Muita gente parada na mesma casa', diz ele." },
    { titulo: "PREVISÃO DO TEMPO", corpo: "Sol entre nuvens e pancadas de dados isoladas. ${nome} deve levar guarda-chuva." },
    { titulo: "ROTINA", corpo: "Mais um dia, mais um dado. ${nome} cumpre seu papel de cidadão do tabuleiro." },
    { titulo: "SEM NOVIDADES", corpo: "Nenhuma fofoca nova no bairro. ${nome} está entediado com a calmaria." },
    { titulo: "PASSEIO", corpo: "${nome} passeia pela cidade observando a arquitetura. Nada comprou, nada vendeu." },
    { titulo: "VIDA NORMAL", corpo: "A vida segue normal para ${nome}. Nem rico, nem pobre, apenas existindo." },
    { titulo: "JOGO MORNO", corpo: "Comentaristas dizem que o jogo está morno. ${nome} precisa agitar as coisas." },
    { titulo: "SILÊNCIO", corpo: "Um silêncio paira sobre a mesa. ${nome} concentra-se na sua próxima jogada." },
    { titulo: "OBSERVADOR", corpo: "${nome} observa os movimentos dos adversários. Estuda estratégias em silêncio." },
    { titulo: "MARCHA LENTA", corpo: "O jogo anda em marcha lenta. ${nome} parece estar com o freio de mão puxado." },
    { titulo: "EQUILÍBRIO", corpo: "As forças estão equilibradas. ${nome} mantém sua posição sem grandes riscos." },
    { titulo: "NORMALIDADE", corpo: "A normalidade é entediante, mas segura. ${nome} não reclama da falta de emoção." },
    { titulo: "CALMARIA", corpo: "A calmaria reina. ${nome} aproveita para contar seu dinheiro e planejar o futuro." },
    { titulo: "SEM EVENTOS", corpo: "O sismógrafo do jogo não registrou abalos. ${nome} caminha em terreno firme." },
    { titulo: "DIA ÚTIL", corpo: "É um dia útil comum no Banco Imobiliário. ${nome} bate cartão e segue o fluxo." },
    { titulo: "STATUS QUO", corpo: "${nome} mantém o status quo. Ninguém sobe, ninguém desce." },
    { titulo: "PAISAGEM", corpo: "${nome} elogia a paisagem do tabuleiro. 'Bonitas casas', comenta educadamente." },
    { titulo: "CAMINHADA", corpo: "${nome} faz sua caminhada matinal pelo tabuleiro. O exercício é bom para a saúde financeira." },
    { titulo: "SEM SURPRESAS", corpo: "${nome} gosta de dias sem surpresas. O coração agradece a estabilidade." },
    { titulo: "ORDEM E PROGRESSO", corpo: "Tudo em ordem na vez de ${nome}. O progresso é lento, mas constante." },
    { titulo: "NA MÉDIA", corpo: "O desempenho de ${nome} está na média. Nem gênio, nem desastre." },
    { titulo: "PONTO MORTO", corpo: "O jogo parece estar em ponto morto. ${nome} tenta engatar uma primeira." },
    { titulo: "BRISA LEVE", corpo: "Uma brisa leve sopra no tabuleiro. ${nome} sente o vento da mudança, mas ele ainda não chegou." },
    { titulo: "RELÓGIO", corpo: "${nome} olha para o relógio. O tempo passa e a fortuna não chega." },
    { titulo: "PACIÊNCIA", corpo: "A virtude de ${nome} hoje é a paciência. Ele espera sua hora chegar." },
    { titulo: "SEM MANCHETE", corpo: "O editor do jornal não achou nada interessante sobre ${nome} para colocar na capa hoje." },
    { titulo: "CONTINUE A NADAR", corpo: "Como diz a Dory: 'Continue a nadar'. ${nome} segue o conselho e continua a jogar." }
  ]
};