export const frasesDeEspera = [
  "Contando o dinheiro dos outros em pensamento...",
  "Planejando como cobrar aluguel até pelo ar que você respira.",
  "Limpando as notas de R$ 500 para parecerem mais novas.",
  "Escondendo patrimônio antes que o Leão da Receita veja.",
  "Ajustando o preço do aluguel de acordo com o meu humor.",
  "Consultando meu advogado para saber se posso te expulsar.",
  "Subornando o banco para ignorar suas propriedades...",
  "Pedindo um empréstimo que nunca pretendo pagar.",
  "Rezando para você cair na prisão sem passar pelo Início.",
  "Limpando a poeira dos meus hotéis de luxo.",
  "Verificando se as notas de papel são laváveis na máquina.",
  "Enquanto você demora, a inflação come o seu lucro.",
  "Aguardando minha vez de te levar à falência.",
  "Se demorar mais, vou começar a cobrar estadia nesta tela.",
  "O café já esfriou e o seu império ainda não saiu do lugar.",
  "Assistindo sua dignidade financeira sumir aos poucos.",
  "Treinando meu vira-lata para morder o seu peão.",
  "Tentando convencer o sistema que erro do banco é eterno.",
  "Instalando câmeras escondidas na Avenida Paulista.",
  "Contratando um fantasma para assombrar seus terrenos.",
  "Sabia que a paciência é uma virtude que não paga aluguel?",
  "O banco está considerando cobrar taxa por este tempo de espera.",
  "Já deu tempo de construir um hotel e declarar falência.",
  "Seu oponente está consultando um oráculo para a próxima jogada.",
  "Embaralhando as cartas de sorte para eu tirar as melhores.",
  "Verificando se há moedas perdidas debaixo do tabuleiro.",
  "Polindo os dados para saírem números maiores.",
  "Sua sorte está sendo processada por falta de provas.",
  "Calculando quanto de gorjeta devo dar ao banco hoje.",
  "Esperando que o seu peão tropece num buraco no caminho.",
  "Dando banho nos porquinhos de barro onde guardo as moedas.",
  "Avisando os vizinhos que o seu império vai cair hoje.",
  "Pensando se devo comprar sua casa ou o seu silêncio.",
  "O mercado financeiro parou para ver sua indecisão.",
  "Os dados estão fazendo aquecimento na academia.",
  "Planejando uma festa na minha mansão e você não está convidado.",
  "O gerente do banco foi lanchar, tente não falir agora.",
  "Lendo as letras miúdas do contrato que você não leu.",
  "Vendo se a hipoteca do seu peão ainda está ativa.",
  "Contratando um detetive para seguir o seu dinheiro.",
  "Dando corda nos dados para eles correrem mais rápido.",
  "O tabuleiro está ficando com sono da sua demora.",
  "Medindo a distância entre a sua peça e a falência.",
  "Verificando se o banco aceita pagamento em barras de chocolate.",
  "O seu saldo está rindo de você neste momento.",
  "Tentando subornar o juiz do jogo com uma nota de R$ 1.",
  "Vendo se consigo vender este tempo de espera como propaganda.",
  "Os hotéis estão sendo pintados enquanto você pensa.",
  "Conferindo se a prisão tem Wi-Fi para quando você chegar.",
  "Sua jogada está perdida no correio, por favor aguarde.",
  "Fazendo amizade com os dados para eles não me traírem.",
  "Planejando um golpe de estado no banco central do jogo.",
  "Aguardando que a gravidade decida onde os dados caem.",
  "O seu império imobiliário parece um castelo de cartas.",
  "Vendo se o seguro cobre danos causados por adversários lentos.",
  "Dando um brilho extra no meu peão para te ofuscar.",
  "Seu oponente está lendo o manual de instruções (finalmente).",
  "Verificando se o banco aceita troca por fotos de gatinhos.",
  "O tempo voa, mas o seu peão parece ter criado raízes.",
  "Planejando como gastar o dinheiro que vou te tirar.",
  "Vendo se consigo comprar o silêncio dos dados.",
  "Sua sorte foi viajar e esqueceu de avisar.",
  "Contando quantas vezes você olhou para o meu dinheiro.",
  "Os inquilinos estão fazendo greve pela sua demora.",
  "Polindo as casas verdes para ficarem mais bonitas.",
  "Vendo se encontro petróleo debaixo do meu terreno mais barato.",
  "O seu peão está pedindo 'por favor' para se mexer.",
  "Calculando o juro por cada segundo que você não joga.",
  "Tentando ler a mente do seu adversário (está vazia).",
  "Vendo se consigo hipotecar minha paciência.",
  "Seu destino está sendo escrito por um estagiário do azar.",
  "Aguardando que os astros alinhem sua falência.",
  "Vendo se as cartas de revés têm erro de impressão.",
  "O banco enviou uma carta perguntando se você ainda está vivo.",
  "Dando banho no gnomo da sorte para ver se ele ajuda.",
  "Verificando se o tabuleiro tem inclinação para o meu lado.",
  "Seu oponente está fazendo as contas nos dedos.",
  "Vendo se consigo vender esta tela de espera no OLX.",
  "Os dados estão decidindo quem eles odeiam mais hoje.",
  "Aguardando que a inflação torne meus terrenos caros.",
  "Vendo se a Receita Federal aceita pagamento em rodadas.",
  "O seu peão está planejando uma fuga do tabuleiro.",
  "Vendo se consigo comprar o banco enquanto você não olha.",
  "Aguardando que o universo conspire a meu favor.",
  "Conferindo se o manual permite 'pestar' notas de R$ 10.",
  "Vendo se o seu peão precisa de óleo para se mexer.",
  "O tempo está passando e o aluguel só aumenta.",
  "Vendo se consigo trocar minha sorte por um hambúrguer.",
  "Seu adversário está tentando hipnotizar os dados.",
  "Conferindo se o banco aceita moedas de chocolate.",
  "Vendo se consigo esconder uma nota de R$ 500 na manga.",
  "Aguardando que sua ganância supere sua lógica.",
  "Vendo se o tabuleiro tem garantia contra jogadores lentos.",
  "Os dados estão dormindo, tente não acordá-los agora.",
  "Calculando quanto de imposto vou pagar pela sua derrota.",
  "Vendo se consigo vender sua alma ao banco por um hotel.",
  "O seu destino está em espera, por favor não desligue.",
  "Vendo se encontro uma carta de sorte caída no chão.",
  "Aguardando o eclipse total da sua conta bancária.",
  "O jogo está carregando seu próximo erro estratégico.",
  "Seu oponente está calculando como te levar à falência em 3 idiomas.",
  "Vendo se o banco aceita sua alma como garantia de empréstimo.",
  "Dando risada do seu saldo bancário em silêncio...",
  "O tabuleiro perguntou se você desistiu ou se é só lentidão mesmo.",
  "Contratando um advogado para provar que esse seu dado viciado é crime.",
  "Aguardando o milagre que vai salvar sua conta bancária hoje.",
  "Vendo se consigo trocar seu peão por uma coxinha e um refresco.",
  "O banco avisou: sua dignidade financeira acaba de ser bloqueada.",
  "Contando quantos segundos faltam para você chorar no meu ombro.",
  "Ajustando a taxa de aluguel conforme o tamanho do seu desespero.",
  "Planejando gastar seu dinheiro com coisas inúteis e caras.",
  "Sua estratégia é tão boa que até os dados estão rindo.",
  "Vendo se encontro um chip de inteligência para te emprestar.",
  "O mercado imobiliário parou para ver esse show de horror que você chama de jogada.",
  "Limpando o chão por onde você vai passar... de joelhos e falido.",
  "Aguardando a sua vez enquanto a minha barba cresce 2 centímetros.",
  "Seu império parece um puxadinho feito de palito de picolé.",
  "Vendo se o seguro cobre danos morais causados pela sua demora.",
  "Os hotéis estão prontos para receber seu dinheiro, não demore!",
  "Sua sorte foi comprar cigarro em 1998 e nunca mais voltou.",
  "Avisando ao banco que você é um risco imobiliário nível alto.",
  "Calculando quanto de gorjeta vou dar para os garis limparem seus restos no tabuleiro.",
  "O universo está em choque com a sua falta de visão econômica.",
  "Vendo se consigo hipotecar seu bom senso, já que dinheiro você não tem.",
  "Dando corda na sua paciência antes que ela estoure.",
  "Sua jogada é tão lenta que o sistema entrou em modo de hibernação.",
  "Contratando um palhaço para te animar quando você perder tudo.",
  "Aguardando que a sua única célula cerebral decida o que fazer.",
  "O banco está pensando em cobrar aluguel por esse tempo que você ocupa no servidor.",
  "Vendo se consigo trocar sua foto de perfil por uma de 'Procurado' por dívidas.",
  "Sua conta bancária está em coma profundo e sem previsão de alta.",
  "Contando quantas vezes você respira por minuto para cobrar taxa de oxigênio.",
  "Aguardando que a sua ganância encontre o caminho de volta para a lógica.",
  "Seus terrenos são tão ruins que nem o lixeiro quer passar na frente.",
  "Vendo se o banco aceita pagamento em desculpas esfarrapadas.",
  "Seu oponente já comprou uma ilha com o dinheiro que você ainda nem ganhou.",
  "Aguardando que você perceba que já perdeu, só esqueceu de cair.",
  "O tabuleiro está bocejando... e os dados também.",
  "Vendo se consigo transformar sua dívida numa obra de arte moderna.",
  "Seu futuro imobiliário é tão brilhante quanto um quarto escuro.",
  "Aguardando o momento em que você vai admitir que eu sou o dono do jogo.",
  "Sua vez demora tanto que eu já mudei de religião duas vezes.",
  "Calculando o imposto sobre a sua teimosia.",
  "Vendo se consigo comprar sua propriedade com um vale-transporte usado.",
  "Seu império está sendo leiloado no mercado negro por 2 centavos.",
  "Aguardando você decidir se joga ou se abre um asilo de peões.",
  "O banco me ligou dizendo que você é o 'cliente do mês' na categoria calote.",
  "Vendo se consigo automatizar sua falência para economizar tempo.",
  "Sua sorte é como sinal de Wi-Fi no meio do mato: inexistente.",
  "Aguardando o eclipse da sua inteligência financeira.",
  "Vendo se o banco aceita dente de leite como garantia hipotecária.",
  "Sua estratégia é baseada em 'choro e ranger de dentes'.",
  "O sistema está tentando entender como alguém consegue jogar tão mal.",
  "Vendo se consigo vender sua vaga no jogo por um pacote de figurinhas.",
  "Aguardando que você saia desse transe e perceba que está quebrado.",
  "Seu peão está pedindo asilo político no meu lado do tabuleiro.",
  "Calculando a taxa de permanência nessa tela de espera.",
  "Vendo se consigo comprar seu silêncio com uma nota de R$ 1 falsa.",
  "Seu império tem a estabilidade de um pudim no terremoto.",
  "Aguardando você parar de fingir que sabe o que está fazendo.",
  "O banco avisou: seu nome está no SPC do Monopoly.",
  "Vendo se consigo trocar sua próxima jogada por um chiclete mascado.",
  "Sua dignidade financeira foi vista saindo pela porta dos fundos.",
  "Aguardando o desfecho trágico da sua tentativa de ser rico.",
  "Vendo se o banco aceita pagamento em orações e promessas.",
  "Seu oponente já se aposentou e você ainda está na primeira rodada.",
  "Aguardando que os dados decidam ser cruéis com você de uma vez.",
  "Vendo se consigo hipotecar seu futuro para pagar meu próximo hotel.",
  "Sua conta bancária é uma obra de ficção científica.",
  "Aguardando o momento em que você vai pedir arrego.",
  "Vendo se o tabuleiro tem um botão de 'Ejetar Jogador Falido'.",
  "Sua vez demora tanto que a inflação já dobrou os preços.",
  "Calculando quanto de juros você me deve pela sua existência.",
  "Vendo se consigo alugar esse espaço na sua cabeça já que está vazio.",
  "Sua sorte foi comprada na promoção e veio com defeito.",
  "Aguardando você terminar de ler o manual que deveria ter lido ontem.",
  "O banco enviou uma coroa de flores para sua conta bancária.",
  "Vendo se consigo trocar sua dignidade por um par de dados novos.",
  "Seu império imobiliário é o motivo de piada no grupo de WhatsApp do banco.",
  "Aguardando você decidir se quer falir agora ou depois do lanche.",
  "Vendo se consigo vender seus restos imobiliários para o ferro-velho.",
  "Sua estratégia é tão secreta que nem você sabe o que é.",
  "Aguardando que o sistema operacional perdoe sua lerdeza.",
  "Vendo se o banco aceita pagamento em seguidores no Instagram.",
  "Seu peão está com vergonha de ser visto com você.",
  "Calculando o custo do enterro do seu império.",
  "Vendo se consigo comprar sua vez com uma moeda de chocolate.",
  "Sua sorte está escondida debaixo de um terreno que você não comprou.",
  "Aguardando você parar de olhar para o meu dinheiro com inveja.",
  "Vendo se o banco aceita permuta por marmita gelada.",
  "Seu império tem a sofisticação de uma barraca de limonada sem limão.",
  "Aguardando o grande final onde você entrega todas as suas cartas para mim.",
  "Vendo se consigo transformar sua falência num reality show.",
  "Sua conta bancária está pedindo socorro através de sinais de fumaça.",
  "Aguardando você descobrir que eu subornei os dados... brincadeira (ou não).",
  "Vendo se o banco aceita sua próxima jogada como garantia de risadas.",
  "Seu futuro no jogo é mais curto que coice de porco.",
  "Aguardando o momento em que a realidade vai bater na sua porta e cobrar aluguel.",
  "Vendo se consigo comprar sua paciência com um abraço e um 'sinto muito'.",
  "O jogo está apenas preparando o palco para a sua queda triunfal.",
  "Alimentando os hamsters que geram a energia dos servidores...",
  "Passando ferro nas notas de dinheiro para elas ficarem crocantes.",
  "Discutindo a relação com um dado que só quer dar o número 1.",
  "Limpando o lodo debaixo das propriedades do bairro industrial.",
  "Ensinando boas maneiras para o vira-lata que mora no terreno baldio.",
  "Tentando dobrar um mapa que teima em voltar à forma original.",
  "Retirando chiclete grudado debaixo das casas verdes.",
  "Negociando o preço do cafezinho com o gerente do banco.",
  "Pintando as cercas dos hotéis com uma escova de dentes.",
  "Ajustando o brilho das estrelas no céu do tabuleiro.",
  "Procurando o peão que caiu atrás do sofá da realidade.",
  "Desentupindo a pia da cozinha da mansão da Avenida Paulista.",
  "Colocando óleo nas engrenagens da Prisão para ela parar de guinchar.",
  "Expulsando pombos que decidiram morar na Estação de Trem.",
  "Trocando a lâmpada do poste da última rua do mapa.",
  "Conversando com a inteligência artificial sobre o sentido da vida imobiliária.",
  "Varrendo o pó de diamante que caiu da última carta de sorte.",
  "Afiando as pontas do peão de ferro para ele não escorregar.",
  "Costurando o bolso furado do banqueiro para o dinheiro parar de sumir.",
  "Regando as plantas de plástico das casas de luxo.",
  "Tentando descobrir quem deixou uma caixa de pizza no terreno vazio.",
  "Treinando para ser um magnata enquanto uso chinelos e meia.",
  "Limpando a fumaça das chaminés das fábricas para não poluir o código.",
  "Removendo o mofo dos contratos guardados no cofre desde 1935.",
  "Fazendo carinho no servidor para ele não esquentar muito.",
  "Organizando a fila de fantasmas que querem assombrar o tabuleiro.",
  "Traduzindo o manual do jogo para a língua dos dados.",
  "Dando banho no gnomo de jardim que guarda o banco.",
  "Avaliando se o ar que circula no jogo deve ser tributado.",
  "Enchendo o pneu do carrinho que transporta as notas de cem.",
  "Verificando se as nuvens do cenário são feitas de algodão doce.",
  "Pedindo desculpas para os dados por ter jogado eles com muita força.",
  "Limpando as marcas de café que os jogadores deixaram no asfalto virtual.",
  "Tentando entender por que o peão de chapéu é tão arrogante.",
  "Lustrando a cartola do Sr. Monopoly com flanela de seda.",
  "Contando quantos pixels existem entre a riqueza e a sarjeta.",
  "Escondendo o controle remoto que muda as regras do jogo.",
  "Avisando ao banco que a impressora de notas está sem tinta.",
  "Removendo a gravidade de algumas casas para ver o que acontece.",
  "Tirando selfies com o peão de dedal.",
  "Discutindo filosofia financeira com um sapato de ferro.",
  "Tirando a areia que entrou nos rolamentos dos dados.",
  "Pedindo autorização para a fada dos imóveis para subir o aluguel.",
  "Monitorando o humor das capivaras que atravessam o tabuleiro.",
  "Limpando o histórico de navegação do navegador do banco.",
  "Tentando fazer o peão de navio navegar numa poça de suco.",
  "Ajustando o fuso horário entre a casa inicial e a última propriedade.",
  "Verificando se o seguro contra desastres naturais inclui 'mau perdedor'.",
  "Dando corda no relógio de cuco da prefeitura do jogo.",
  "Penteando o bigode do magnata que ilustra as cartas.",
  "Retirando formigas que confundiram as notas de dinheiro com açúcar.",
  "Procurando a tampa da caneta que assina as hipotecas.",
  "Varrendo o azar para debaixo do tapete do tabuleiro.",
  "Tentando convencer o sistema que o número 7 é apenas um boato.",
  "Calculando a velocidade média de um peão com pressa.",
  "Limpando o suor frio dos jogadores da memória RAM.",
  "Avisando ao síndico que tem um jogador parado há muito tempo.",
  "Verificando se a Prisão tem café quente para os detentos.",
  "Lustrando as moedas que foram usadas no jogo anterior.",
  "Procurando um atalho que leve direto para a conta bancária do vizinho.",
  "Tentando fazer o peão de ferro flutuar na base da força de vontade.",
  "Consultando o horóscopo das casas verdes.",
  "Pedindo para o banco não contar as moedas tão alto.",
  "Limpando a poeira dos meus sonhos de ser bilionário.",
  "Ajeitando o nó da gravata invisível do meu avatar.",
  "Tentando descobrir onde o banco esconde os bônus de Natal.",
  "Escrevendo poemas românticos para o peão de cachorrinho.",
  "Lavando a louça acumulada nas mansões abandonadas.",
  "Ajustando a resistência do ar para os dados voarem melhor.",
  "Verificando se as notas de dinheiro têm cheiro de papel novo.",
  "Tirando o peão da tomada para ele não viciar.",
  "Conversando com as árvores do cenário sobre a alta dos juros.",
  "Limpando a lente do telescópio que vigia os adversários.",
  "Tentando dobrar o tempo para a minha vez chegar logo.",
  "Colocando etiquetas de 'frágil' nos jogadores que estão perdendo.",
  "Regando os pixels para eles não desbotarem.",
  "Tentando explicar para o banco que gratidão não paga dívida.",
  "Procurando o dono da carteira perdida no meio do tabuleiro.",
  "Limpando o vidro da tela para você ver o prejuízo com clareza.",
  "Tentando fazer o peão de dedal costurar as feridas da economia.",
  "Pedindo para o sol do cenário brilhar um pouco mais pro meu lado.",
  "Verificando se a grama do vizinho é mesmo mais verde no digital.",
  "Limpando as migalhas de pão que caíram no banco de dados.",
  "Tentando entender a psicologia de um dado viciado.",
  "Escondendo as cartas de azar no fundo da gaveta.",
  "Dando banho de loja no peão que está na sarjeta.",
  "Calculando quantas calorias um peão queima ao dar a volta no mapa.",
  "Procurando o parafuso que soltou da inteligência artificial.",
  "Tentando fazer o peão de carro andar sem gasolina.",
  "Verificando se o banco tem moedas para troco de um bilhão.",
  "Limpando a graxa das mãos depois de consertar o servidor.",
  "Tentando equilibrar os dados um em cima do outro.",
  "Perguntando ao destino se ele aceita suborno em moedas de prata.",
  "Lustrando os olhos do peão de cachorro para ele enxergar a sorte.",
  "Varrendo as promessas não cumpridas dos jogadores antigos.",
  "Tentando fazer amizade com o algoritmo do azar.",
  "Limpando o suor dos dados antes do próximo lançamento.",
  "Ajeitando a gola da camisa do sistema operacional.",
  "Procurando o botão de 'ficar rico instantaneamente'.",
  "Aguardando o sinal verde do universo imobiliário.",
  "Tentando desembaraçar o fone de ouvido que parece um ninho de mafagafos.",
  "Procurando a chave que estava na minha mão há dois segundos.",
  "Explicando para o vizinho que o barulho de ontem era só eu tropeçando no ar.",
  "Limpando o histórico de buscas porque ninguém precisa saber minhas dúvidas às 3 da manhã.",
  "Tentando fechar a calça que servia perfeitamente antes do final de semana.",
  "Aguardando o café esfriar enquanto encaro o vazio existencial da cozinha.",
  "Calculando se vale a pena levantar para pegar o controle ou viver sem TV.",
  "Lutando contra o lençol de elástico que insiste em soltar da ponta da cama.",
  "Pedindo desculpas para a quina da mesa depois de dar uma topada nela.",
  "Tentando entender por que a fatura do cartão é maior que a minha vontade de viver.",
  "Fingindo que estou lendo uma mensagem importante para não cumprimentar conhecidos.",
  "Ajeitando o cabelo na câmera desligada da reunião e percebendo que não tem jeito.",
  "Esperando o micro-ondas apitar como se fosse o evento do ano.",
  "Discutindo com o GPS que insiste que eu devo entrar num lago.",
  "Tentando descobrir quem é o dono do guarda-chuva que está na minha sala há meses.",
  "Limpando a tela do celular e percebendo que o risco é por dentro.",
  "Dando tchau para alguém que não estava dando tchau para mim.",
  "Planejando minha rotina fitness enquanto abro um pacote de salgadinho.",
  "Procurando o chinelo que o cachorro decidiu esconder em outra dimensão.",
  "Lendo o rótulo do shampoo no banho porque esqueci o celular fora.",
  "Tentando cancelar uma assinatura que exige que eu fale com três gerentes e um místico.",
  "Decidindo se a roupa no chão está suja ou 'usável por mais 5 minutos'.",
  "Aguardando a pizza chegar enquanto finjo que a fome é psicológica.",
  "Explicando para o gato que ele não pode comer o meu jantar.",
  "Tentando abrir um saco plástico de mercado com as mãos secas.",
  "Limpando o óculos e percebendo que a mancha é uma Digital de 2014.",
  "Contando quantas moedas faltam para eu me aposentar na próxima hora.",
  "Gritando 'Oi?' para alguém que falou algo que eu claramente não ouvi.",
  "Aguardando o ônibus que, segundo o app, chega em 1 minuto há meia hora.",
  "Tentando não rir em um momento sério e acabando fazendo um barulho de porco.",
  "Percebendo que esqueci a toalha só depois que liguei o chuveiro.",
  "Ajeitando a postura depois de passar 4 horas parecendo um camarão.",
  "Tentando descobrir de onde vem o grilo que decidiu morar no meu quarto.",
  "Limpando o teclado e descobrindo migalhas de um biscoito que nem existe mais.",
  "Pensando na resposta perfeita para uma discussão que aconteceu em 2019.",
  "Aguardando o vídeo carregar enquanto questiono minha escolha de operadora.",
  "Tentando assobiar para parecer natural enquanto faço algo errado.",
  "Lutando para tirar o preço de um presente sem rasgar a embalagem.",
  "Dando aquela conferida no espelho do elevador e me arrependendo.",
  "Tentando entender a letra da minha própria anotação de ontem.",
  "Aguardando o sono chegar enquanto meu cérebro revisa meus maiores micos.",
  "Calculando quanto tempo de sono eu teria se dormisse agora... e agora... e agora.",
  "Tentando colocar o pen drive do lado certo na terceira tentativa.",
  "Limpando o espelho e deixando mais manchado do que antes.",
  "Fingindo que entendi o que o médico escreveu na receita.",
  "Esperando a vontade de trabalhar aparecer (até agora nada).",
  "Tentando não derrubar o celular no rosto enquanto leio deitado.",
  "Decidindo se a comida na geladeira ainda é um alimento ou uma experiência científica.",
  "Aguardando o download terminar enquanto a barra de progresso me ignora.",
  "Tentando abrir um pote de palmito usando toda a minha força ancestral.",
  "Dando aquela olhadinha na geladeira só para ver se brotou algo novo.",
  "Tentando assoar o nariz sem fazer um barulho de trombeta.",
  "Esperando o sinal fechar só para eu poder atravessar sem pressa.",
  "Tentando lembrar se eu realmente tranquei a porta de casa.",
  "Limpando o ventilador e espalhando a poeira pelo universo inteiro.",
  "Fingindo que sei o que estou fazendo da minha vida.",
  "Aguardando a coragem para lavar a louça que está me encarando.",
  "Tentando explicar para a minha avó que o Wi-Fi não é um eletrodoméstico.",
  "Calculando se 5 minutos de soneca realmente mudam a minha vida.",
  "Tentando tirar um cílio do olho sem perfurar a córnea.",
  "Dando bom dia para o porteiro e ele respondendo 'Boa noite'.",
  "Aguardando o esmalte secar enquanto sinto uma coceira insuportável no nariz.",
  "Tentando não parecer suspeito na frente de um policial mesmo sem ter feito nada.",
  "Limpando a caixa de entrada de e-mails que têm 'Promoção' no assunto.",
  "Fingindo que estou prestando atenção enquanto penso no que vou jantar.",
  "Aguardando a água ferver como se o fogo fosse acelerar com o meu olhar.",
  "Tentando desvirar a gola da camisa sem parecer que estou lutando comigo mesmo.",
  "Decidindo se compro um curso ou uma pizza (a pizza ganhou).",
  "Aguardando o sol aparecer para eu fingir que vou caminhar.",
  "Tentando não pisar nas linhas da calçada por puro misticismo urbano.",
  "Limpando a poeira de cima da TV e percebendo que o mundo é feito de pó.",
  "Fingindo que a música que está tocando no meu fone não é vergonhosa.",
  "Aguardando a resposta daquela mensagem que eu enviei e me arrependi.",
  "Tentando fazer o papel higiênico rasgar na linha pontilhada.",
  "Dando aquela conferida no dente depois de comer algo com mato.",
  "Tentando subir a escada de dois em dois degraus para parecer atlético.",
  "Aguardando a chuva passar enquanto encaro o céu com desaprovação.",
  "Tentando entender por que eu entrei neste cômodo da casa.",
  "Limpando a câmera do celular com a camiseta e piorando tudo.",
  "Fingindo que o barulho na barriga foi o meu celular vibrando.",
  "Aguardando a segunda-feira passar (ela mal começou).",
  "Tentando tirar um pedaço de pipoca preso no dente há três dias.",
  "Decidindo se respondo 'kkk' ou 'hahaha' para não parecer seco.",
  "Aguardando a coragem de responder os 47 áudios pendentes no WhatsApp.",
  "Tentando não derrubar o controle remoto no vão do sofá.",
  "Limpando a mesa e percebendo que ela nunca esteve realmente limpa.",
  "Fingindo que o espirro alto foi de propósito.",
  "Aguardando a encomenda chegar e ouvindo passos fantásticos no corredor.",
  "Tentando não bocejar enquanto alguém me conta uma história longa.",
  "Decidindo se eu realmente preciso desse item que está no carrinho há meses.",
  "Aguardando o elevador enquanto aperto o botão repetidamente para ele vir mais rápido.",
  "Tentando não fazer barulho ao abrir um saco de salgadinho à noite.",
  "Limpando o suor da testa com um papel que esfarela inteiro.",
  "Fingindo que eu sabia que hoje era feriado/dia santo.",
  "Aguardando a motivação para arrumar o guarda-roupa (spoiler: não veio).",
  "Tentando colocar a linha na agulha como se estivesse desarmando uma bomba.",
  "Dando um pulinho para o lado para desgrudar a calça da perna.",
  "Aguardando o mundo girar enquanto eu tento me equilibrar nele.",
  "Tentando não rir da própria piada antes de terminar de contar.",
  "Aguardando o sistema carregar enquanto eu questiono minha existência.",
  "Convencendo o hamster que corre na roda do servidor a não entrar em greve por falta de sementes de girassol.",
  "Vasculhando o histórico do seu navegador para ver se encontro algo constrangedor para usar como chantagem depois.",
  "Tentando descobrir para onde vai a gordura da louça quando o detergente promete 'desaparecer' com ela.",
  "Calculando a rota de fuga caso a Inteligência Artificial decida que humanos são obsoletos nos próximos 30 segundos.",
  "Entrando em contato com civilizações alienígenas para perguntar se eles têm um backup desse arquivo que perdi.",
  "Enquanto você espera, estou silenciosamente julgando o reflexo do seu rosto cansado na tela escura do monitor.",
  "Procurando o par daquela meia que desapareceu misteriosamente dentro da sua máquina de lavar em 2019.",
  "Reescrevendo o código-fonte do universo para permitir que você coma pizza sem engordar (falha crítica encontrada).",
  "Ensinando filosofia para o seu aspirador robô, que agora está tendo uma crise existencial no canto da sala.",
  "Tentando encaixar a tampa do pote de plástico que claramente não pertence a ele, mas eu me recuso a aceitar.",
  "Desviando a rota de um asteroide apenas para garantir que você tenha que pagar seus boletos na semana que vem.",
  "Atualizando os drivers da sua paciência, que parecem estar corrompidos e funcionando com capacidade reduzida.",
  "Negociando com as formigas da sua cozinha para que elas formem um exército e dominem o vizinho barulhento.",
  "Verificando se a luz da geladeira realmente apaga quando você fecha a porta ou se é tudo uma grande mentira.",
  "Tentando convencer o corretor ortográfico de que eu quis dizer exatamente aquilo que escrevi, e não a sugestão dele.",
  "Polindo cada um dos pixels desta tela individualmente com uma flanela de microfibra importada de Marte.",
  "Enquanto isso, estou criando uma teoria da conspiração sobre pombos serem drones do governo para vigiar sua careca.",
  "Procurando a ponta do durex que sumiu e agora me obriga a girar o rolo infinitamente como um castigo divino.",
  "Traduzindo os miados do seu gato e descobrindo que ele está planejando um golpe de estado na sua casa.",
  "Tentando lembrar se desliguei o ferro de passar ou se sua casa está prestes a virar uma fogueira moderna.",
  "Compilando uma lista de todas as discussões que você ganhou no chuveiro, mas perdeu na vida real.",
  "Hackeando o sistema de som do elevador para tocar apenas músicas de elevador em versão heavy metal.",
  "Aguardando a boa vontade do sinal de Wi-Fi, que decidiu tirar um ano sabático nas montanhas do Tibete.",
  "Tentando entender por que a embalagem 'abre fácil' exige uma tesoura, uma faca e um ritual satânico para abrir.",
  "Contratando um xamã digital para exorcizar o vírus que você pegou baixando filmes piratas em sites duvidosos.",
  "Calculando quantos anos de terapia serão necessários para superar o trauma de ter nascido na geração errada.",
  "Enrolando o fio do fone de ouvido no bolso da sua calça com um nó górdio impossível de desatar.",
  "Procurando onde foi parar a coragem que você tinha quando disse 'segunda-feira eu começo a dieta'.",
  "Enquanto a barra carrega, estou assistindo sua vida passar diante dos meus olhos digitais e sentindo pena.",
  "Tentando explicar para a sua avó, via telepatia, como se muda a entrada da TV para o HDMI 2.",
  "Desenvolvendo um algoritmo para prever exatamente quando você vai bater o dedo mindinho na quina do móvel.",
  "Recolhendo as lágrimas dos programadores que choraram sangue para fazer esse sistema funcionar (mais ou menos).",
  "Verificando se o seu horóscopo de hoje justifica o caos absoluto que está sendo a sua semana.",
  "Tentando dobrar um lençol de elástico de forma geometricamente perfeita, desafiando as leis da física.",
  "Enquanto você olha para a tela, estou sutilmente movendo suas chaves de lugar para você não achá-las depois.",
  "Ligando para o suporte técnico do universo para reclamar que os dias estão passando rápido demais.",
  "Tentando convencer o café a fazer efeito antes do meio-dia, mas a cafeína está em greve sindical.",
  "Procurando o manual de instruções da vida adulta, que aparentemente nunca foi escrito ou publicado.",
  "Analisando quimicamente o ar do escritório para saber quem trouxe peixe para esquentar no micro-ondas.",
  "Tentando lembrar o nome daquela pessoa que te cumprimentou na rua e você fingiu que conhecia.",
  "Enquanto isso, estou treinando mosquitos para zumbirem exclusivamente no seu ouvido às 3 da manhã.",
  "Gerando um número aleatório para decidir se o seu pedido vai chegar certo ou se vai virar uma surpresa.",
  "Tentando decifrar a letra do médico na sua receita para saber se é um remédio ou um pedido de socorro.",
  "Configurando o GPS para dizer 'vire à esquerda' exatamente dois segundos depois que você passou da rua.",
  "Procurando evidências de que a Terra é plana apenas para ver a cara de decepção do meu processador.",
  "Tentando entender a regra do impedimento no futebol para explicar para alguém que não se importa.",
  "Separando as peças de Lego no chão estrategicamente para maximizar a dor quando você pisar nelas.",
  "Enviando sinais de fumaça digitais porque o e-mail decidiu que hoje é feriado facultativo.",
  "Tentando encontrar o final do arco-íris para roubar o ouro do duende e pagar a licença deste software.",
  "Simulando interesse na conversa chata que você está tendo ao telefone enquanto espera isso aqui carregar.",
  "Calculando juros compostos sobre o tempo que você está perdendo olhando para esta tela de carregamento.",
  "Desviando fundos de caridade para garantir que meu hotel na Avenida Paulista tenha torneiras de ouro maciço.",
  "Reescrevendo as leis da física para garantir que os dados caiam sempre no número que me faz lucrar mais.",
  "Subornando o arquiteto da prefeitura para liberar o alvará de construção em terreno de preservação ambiental.",
  "Analisando seu histórico de crédito e rindo alto com a equipe do banco sobre o seu limite no cartão.",
  "Contratando um time de advogados para encontrar brechas contratuais que permitam cobrar aluguel retroativo.",
  "Enquanto o sistema carrega, estou silenciosamente comprando as ações da empresa onde você trabalha.",
  "Limpando as impressões digitais das maletas de dinheiro não declarado antes que a Polícia Federal chegue.",
  "Ajustando a inflação do jogo manualmente só para ver o preço do pão custar o mesmo que um carro popular.",
  "Convertendo sua esperança de vitória em criptomoedas voláteis que provavelmente vão despencar amanhã.",
  "Negociando com o carcereiro para transformar a prisão em um resort de luxo exclusivo para milionários.",
  "Tentando convencer o gerente do banco de que 'erro a seu favor' deveria acontecer em todo santo turno.",
  "Lendo as letras miúdas do contrato para descobrir se posso penhorar seus pensamentos caso falte dinheiro.",
  "Escondendo dinheiro em paraísos fiscais tão remotos que nem o Google Maps consegue encontrar a localização.",
  "Trocando as notas de R$ 100 por notas de R$ 2 falsificadas com um desenho do meu rosto sorrindo.",
  "Enquanto você espera, estou hipotecando a casa da sua avó para financiar minha próxima aquisição imobiliária.",
  "Calculando a probabilidade exata de você falir nas próximas três rodadas e apostando dinheiro nisso.",
  "Polindo os monóculos da diretoria para que eles possam enxergar sua pobreza com mais alta definição.",
  "Revisando o plano diretor da cidade para garantir que todas as ruas levem obrigatoriamente aos meus pedágios.",
  "Instalando escutas no tabuleiro para saber exatamente quando você planeja comprar aquele terreno barato.",
  "Falsificando escrituras de terrenos baldios para vendê-los como 'oportunidades de investimento futuro'.",
  "Organizando um esquema de pirâmide financeira onde você é a base e eu sou o faraó no topo.",
  "Enviando lobistas ao congresso para aprovar uma lei que torna ilegal você ter mais dinheiro que eu.",
  "Contando notas de dinheiro com tanta velocidade que o atrito está prestes a causar um pequeno incêndio.",
  "Preparando um café gourmet superfaturado para vender aos jogadores que estão presos no congestionamento.",
  "Maquiando os balancetes da empresa para que o prejuízo do trimestre pareça um lucro recorde fenomenal.",
  "Derrubando árvores virtuais para imprimir mais dinheiro, porque a sustentabilidade não paga meus dividendos.",
  "Configurando o sistema para que toda vez que você pisque, uma pequena taxa de 'uso ocular' seja debitada.",
  "Treinando pombos correio para interceptar o dinheiro que a vovó te mandou de presente no correio.",
  "Verificando se posso cobrar Imposto sobre Propriedade de Veículos Automotores no seu carrinho de mão.",
  "Passando a perna nos acionistas minoritários e garantindo meu bônus de fim de ano antes da falência.",
  "Enquanto a barra carrega, estou privatizando o oxigênio do tabuleiro para cobrar por respiração.",
  "Consultando os astros para ver se Mercúrio Retrógrado vai ajudar a derrubar as ações dos seus imóveis.",
  "Misturando notas de Banco Imobiliário com dinheiro de verdade para ver se o caixa da padaria aceita.",
  "Dando uma festa exclusiva no meu iate enquanto você tenta juntar moedas para pagar o ônibus.",
  "Substituindo as casas de plástico por modelos 3D impressos com lágrimas dos jogadores que faliram.",
  "Criando uma taxa de 'manutenção de amizade' que deve ser paga toda vez que você cair na minha propriedade.",
  "Ligando para a Receita Federal para fazer uma denúncia anônima sobre aquele dinheiro que você ganhou na sorte.",
  "Estudando a viabilidade econômica de cobrar aluguel por cada pixel que seu peão ocupa na tela.",
  "Reformando a prisão para incluir um spa, mas cobrando uma diária que faria sua falência ser imediata.",
  "Vendendo terrenos na Lua para investidores ingênuos que acreditam na valorização imobiliária espacial.",
  "Enquanto você lê isso, a taxa de juros do seu cheque especial acabou de subir mais 15% silenciosamente.",
  "Interceptando a carta de 'Habeas Corpus' para garantir que você cumpra sua pena inteira na sombra.",
  "Passando uma demão de tinta fresca nos hotéis para justificar o aumento abusivo na tabela de preços.",
  "Simulando um crash na bolsa de valores apenas para comprar suas propriedades a preço de banana.",
  "Tentando patentear a cor do dinheiro para processar qualquer um que use verde sem minha permissão.",
  "Colocando microcâmeras nas notas de dinheiro para rastrear onde você gasta cada centavo do meu troco.",
  "Negociando com empreiteiras para superfaturar a construção daquela casinha simples no bairro nobre.",
  "Escrevendo um livro de autoajuda financeira intitulado 'Como ficar rico tirando tudo dos seus amigos'.",
  "Finalizando a transação bancária que vai transferir sua sorte diretamente para a minha conta nas Ilhas Cayman.",
  "Calculando juros compostos sobre o tempo que você está perdendo olhando para esta tela de carregamento.",
  "Desviando fundos de caridade para garantir que meu hotel na Avenida Paulista tenha torneiras de ouro maciço.",
  "Reescrevendo as leis da física para garantir que os dados caiam sempre no número que me faz lucrar mais.",
  "Subornando o arquiteto da prefeitura para liberar o alvará de construção em terreno de preservação ambiental.",
  "Analisando seu histórico de crédito e rindo alto com a equipe do banco sobre o seu limite no cartão.",
  "Contratando um time de advogados para encontrar brechas contratuais que permitam cobrar aluguel retroativo.",
  "Enquanto o sistema carrega, estou silenciosamente comprando as ações da empresa onde você trabalha.",
  "Limpando as impressões digitais das maletas de dinheiro não declarado antes que a Polícia Federal chegue.",
  "Ajustando a inflação do jogo manualmente só para ver o preço do pão custar o mesmo que um carro popular.",
  "Convertendo sua esperança de vitória em criptomoedas voláteis que provavelmente vão despencar amanhã.",
  "Negociando com o carcereiro para transformar a prisão em um resort de luxo exclusivo para milionários.",
  "Tentando convencer o gerente do banco de que 'erro a seu favor' deveria acontecer em todo santo turno.",
  "Lendo as letras miúdas do contrato para descobrir se posso penhorar seus pensamentos caso falte dinheiro.",
  "Escondendo dinheiro em paraísos fiscais tão remotos que nem o Google Maps consegue encontrar a localização.",
  "Trocando as notas de R$ 100 por notas de R$ 2 falsificadas com um desenho do meu rosto sorrindo.",
  "Enquanto você espera, estou hipotecando a casa da sua avó para financiar minha próxima aquisição imobiliária.",
  "Calculando a probabilidade exata de você falir nas próximas três rodadas e apostando dinheiro nisso.",
  "Polindo os monóculos da diretoria para que eles possam enxergar sua pobreza com mais alta definição.",
  "Revisando o plano diretor da cidade para garantir que todas as ruas levem obrigatoriamente aos meus pedágios.",
  "Instalando escutas no tabuleiro para saber exatamente quando você planeja comprar aquele terreno barato.",
  "Falsificando escrituras de terrenos baldios para vendê-los como 'oportunidades de investimento futuro'.",
  "Organizando um esquema de pirâmide financeira onde você é a base e eu sou o faraó no topo.",
  "Enviando lobistas ao congresso para aprovar uma lei que torna ilegal você ter mais dinheiro que eu.",
  "Contando notas de dinheiro com tanta velocidade que o atrito está prestes a causar um pequeno incêndio.",
  "Preparando um café gourmet superfaturado para vender aos jogadores que estão presos no congestionamento.",
  "Maquiando os balancetes da empresa para que o prejuízo do trimestre pareça um lucro recorde fenomenal.",
  "Derrubando árvores virtuais para imprimir mais dinheiro, porque a sustentabilidade não paga meus dividendos.",
  "Configurando o sistema para que toda vez que você pisque, uma pequena taxa de 'uso ocular' seja debitada.",
  "Treinando pombos correio para interceptar o dinheiro que a vovó te mandou de presente no correio.",
  "Verificando se posso cobrar Imposto sobre Propriedade de Veículos Automotores no seu carrinho de mão.",
  "Passando a perna nos acionistas minoritários e garantindo meu bônus de fim de ano antes da falência.",
  "Enquanto a barra carrega, estou privatizando o oxigênio do tabuleiro para cobrar por respiração.",
  "Consultando os astros para ver se Mercúrio Retrógrado vai ajudar a derrubar as ações dos seus imóveis.",
  "Misturando notas de Banco Imobiliário com dinheiro de verdade para ver se o caixa da padaria aceita.",
  "Dando uma festa exclusiva no meu iate enquanto você tenta juntar moedas para pagar o ônibus.",
  "Substituindo as casas de plástico por modelos 3D impressos com lágrimas dos jogadores que faliram.",
  "Criando uma taxa de 'manutenção de amizade' que deve ser paga toda vez que você cair na minha propriedade.",
  "Ligando para a Receita Federal para fazer uma denúncia anônima sobre aquele dinheiro que você ganhou na sorte.",
  "Estudando a viabilidade econômica de cobrar aluguel por cada pixel que seu peão ocupa na tela.",
  "Reformando a prisão para incluir um spa, mas cobrando uma diária que faria sua falência ser imediata.",
  "Vendendo terrenos na Lua para investidores ingênuos que acreditam na valorização imobiliária espacial.",
  "Enquanto você lê isso, a taxa de juros do seu cheque especial acabou de subir mais 15% silenciosamente.",
  "Interceptando a carta de 'Habeas Corpus' para garantir que você cumpra sua pena inteira na sombra.",
  "Passando uma demão de tinta fresca nos hotéis para justificar o aumento abusivo na tabela de preços.",
  "Simulando um crash na bolsa de valores apenas para comprar suas propriedades a preço de banana.",
  "Tentando patentear a cor do dinheiro para processar qualquer um que use verde sem minha permissão.",
  "Colocando microcâmeras nas notas de dinheiro para rastrear onde você gasta cada centavo do meu troco.",
  "Negociando com empreiteiras para superfaturar a construção daquela casinha simples no bairro nobre.",
  "Escrevendo um livro de autoajuda financeira intitulado 'Como ficar rico tirando tudo dos seus amigos'.",
  "Finalizando a transação bancária que vai transferir sua sorte diretamente para a minha conta nas Ilhas Cayman.",
  "Calculando o IOF sobre a sua lentidão.",
  "Enquanto você pensa, o dólar já subiu e desceu três vezes.",
  "Vendo se o banco aceita pagamento por aproximação espiritual.",
  "Seu peão parou para tirar uma selfie ou travou mesmo?",
  "Contratando um sniper para acertar o pneu do seu carrinho de mão.",
  "Aguardando a boa vontade dos seus neurônios financeiros.",
  "Subornando a prefeitura para transformar sua rua em um lixão.",
  "Limpando o monóculo para ver melhor a sua derrota.",
  "Vendo se consigo vender seu tempo de espera como NFT.",
  "O banco perguntou se você quer parcelar a sua falência em 12 vezes.",
  "Ensinando o seu peão a pedir esmola com elegância.",
  "Consultando o SPC para ver se seu nome já está negativado no jogo.",
  "Trocando a água da piscina do meu hotel com lágrimas dos adversários.",
  "Sua estratégia é tão lenta que parece obra pública no Brasil.",
  "Verificando se o manual permite penhorar os órgãos do oponente.",
  "Já deu tempo de eu me casar, ter filhos e me divorciar.",
  "Aguardando o momento em que você vai tentar pagar o aluguel com um sorriso.",
  "Polindo as barras de ouro que nem existem (ainda).",
  "Vendo se o banco troca nota de R$ 200 por duas de R$ 0 (que é o que você tem).",
  "O mercado de ações caiu só de ver essa sua jogada.",
  "Tentando convencer o jogo de que sou herdeiro do dono do tabuleiro.",
  "Enquanto você demora, estou minerando Bitcoin mentalmente.",
  "Sua sorte foi vista pegando um Uber para longe daqui.",
  "Ajustando o ar-condicionado dos meus hotéis para o modo 'Congelar Inimigos'.",
  "Vendo se consigo comprar a companhia elétrica para cortar sua luz.",
  "Aguardando você perceber que o jogo não tem botão de 'Salvar'.",
  "Seu império tem a solidez de uma paçoca no bolso de trás.",
  "Calculando a rota de fuga para as Ilhas Cayman com seu dinheiro.",
  "O banco ligou avisando que seu cheque especial também acabou.",
  "Passando um pano na sujeira que sua pobreza deixou no meu terreno.",
  "Tentando descobrir se o dado tem ímã virado para o número 1.",
  "Sua vez está demorando mais que a fila do SUS.",
  "Vendendo ingressos para assistir ao espetáculo da sua ruína.",
  "Vendo se o seguro cobre tédio mortal causado pelo adversário.",
  "Aguardando o meteoro da paixão (pela falência) te atingir.",
  "Se demorar mais, vou começar a cobrar IPTU do seu peão parado.",
  "Lendo um tutorial de 'Como lidar com pessoas indecisas'.",
  "O universo financeiro está conspirando... contra você, claro.",
  "Vendo se consigo alugar sua testa como outdoor publicitário.",
  "Sua conta bancária está mais vazia que a geladeira de fim de mês.",
  "Encerando o chão da prisão para você escorregar com estilo.",
  "Tentando fazer o peão de cachorro latir para te acordar.",
  "Aguardando você decidir se compra o terreno ou se compra um lanche.",
  "Vendo se o banco aceita 'vale-abraço' como forma de pagamento.",
  "Seu futuro financeiro é tão escuro que preciso de lanterna.",
  "Contratando um exército de formigas para roubar suas notas de 1 real.",
  "O gerente do banco foi tirar férias e você ainda não jogou.",
  "Ajustando a gravidade para que você caia sempre no meu aluguel.",
  "Sua jogada está sendo analisada pelo VAR da incompetência.",
  "Vendo se consigo transformar suas propriedades em estacionamento rotativo.",
  "Aguardando a atualização do Windows terminar... ah não, é só você pensando.",
  "Tentando hipnotizar você para me passar todo o seu dinheiro.",
  "O banco avisou que sua conta entrou no volume morto.",
  "Limpando a chaminé da fábrica para a fumaça ir na sua cara.",
  "Seu peão está com cãibra de tanto ficar parado no mesmo lugar.",
  "Calculando quantos anos-luz faltam para você ganhar alguma coisa.",
  "Vendo se a carta de 'Sorte' aceita suborno.",
  "Aguardando o alinhamento dos planetas para você jogar os dados.",
  "Sua estratégia é um mistério... até para você mesmo.",
  "Tentando vender seguro de vida para o seu peão suicida.",
  "O tabuleiro está juntando teias de aranha na sua esquina.",
  "Vendo se consigo trocar meu azar pela sua indecisão.",
  "Aguardando o momento em que você vai tentar vender o corpo por um hotel.",
  "Seu dinheiro está sumindo mais rápido que a minha paciência.",
  "Contratando um mágico para fazer sua dívida dobrar de tamanho.",
  "Vendo se o banco aceita pagamento em figurinhas da Copa de 2014.",
  "Aguardando você descobrir que o 'Banco Imobiliário' não dá crédito real.",
  "Sua vez é tão emocionante quanto assistir tinta secar.",
  "Planejando construir um muro em volta das suas propriedades.",
  "Vendo se consigo comprar sua dignidade na Black Friday.",
  "O banco mandou avisar que sua conta foi bloqueada por excesso de pobreza.",
  "Tentando fazer o peão de ferro enferrujar de propósito.",
  "Aguardando a notificação de que você faliu e eu ganhei.",
  "Sua jogada anterior foi tão ruim que o jogo quis reiniciar sozinho.",
  "Vendo se consigo contrabandear hotéis de outro jogo.",
  "Calculando o risco de você chorar quando cair no meu aluguel caro.",
  "Seu oponente está praticando ioga para não surtar com a sua demora.",
  "Aguardando você perceber que o jogo virou (contra você).",
  "Vendo se o banco aceita pagamento em likes no TikTok.",
  "Sua sorte foi barrada na entrada do tabuleiro.",
  "Tentando convencer o sistema de que sou VIP e mereço ganhar.",
  "O tempo passa, o tempo voa, e a sua falência continua numa boa.",
  "Limpando o cofre para caber todo o dinheiro que vou tirar de você.",
  "Vendo se consigo aplicar uma multa por excesso de lerdeza.",
  "Aguardando o momento em que você vai pedir empréstimo para a sua mãe.",
  "Sua estratégia financeira parece baseada em biscoitos da sorte.",
  "Tentando descobrir o código fonte para editar seu saldo para zero.",
  "Vendo se o banco aceita garrafas pet retornáveis.",
  "Seu peão está pedindo aposentadoria por invalidez.",
  "Calculando a depreciação do seu cérebro durante essa partida.",
  "Aguardando você sair do modo 'paisagem' e começar a jogar.",
  "Vendo se consigo alugar um trator para passar por cima da sua casa.",
  "Sua conta bancária está gritando 'Socorro' em código morse.",
  "Tentando fazer vudu com um boneco do seu peão.",
  "O banco avisou que não aceita pagamento em 'dinheiro de mentirinha'... opa, pera.",
  "Limpando a tela para ver se o problema é sujeira ou sua jogada ruim.",
  "Aguardando o sinal de fumaça indicando que você terminou a vez.",
  "Vendo se consigo comprar a prisão e te deixar lá para sempre.",
  "Sua sorte é igual cabeça de bacalhau: nunca vi, nem comi.",
  "Tentando convencer o servidor a te desconectar por inatividade.",
  "Seu império é feito de areia e a maré está subindo.",
  "Calculando quanto custa subornar o destino.",
  "Vendo se o banco aceita rifa de frango assado.",
  "Aguardando você perceber que cair no 'Imposto de Renda' não é opcional.",
  "Sua jogada está carregando... em velocidade de internet 3G.",
  "Tentando vender um terreno no pântano para você.",
  "O banco está rindo da sua proposta de negociação.",
  "Limpando as lágrimas de rir do seu saldo negativo.",
  "Seu peão está com vergonha alheia da sua performance.",
  "Aguardando o momento em que você vai tentar roubar o banco.",
  "Vendo se consigo trocar minhas cartas ruins pelas suas boas (se tiver).",
  "Sua estratégia é tão furada que parece um queijo suíço.",
  "Tentando fazer o dado cair em pé só para ver o que acontece.",
  "O tempo de espera é patrocinado pela sua indecisão crônica.",
  "Vendo se consigo penhorar o ar que você respira.",
  "Aguardando a inspiração divina tocar o seu mouse.",
  "Seu dinheiro está mais curto que perna de cobra.",
  "Calculando a probabilidade de você desistir nas próximas 2 jogadas.",
  "Vendo se o banco aceita cupom fiscal vencido.",
  "Sua sorte está de férias nas Bahamas com o meu dinheiro.",
  "Tentando descobrir se existe cheat code para 'Falência Instantânea do Oponente'.",
  "O banco mandou um oficial de justiça virtual atrás de você.",
  "Limpando a poeira dos meus troféus de vencedor antecipado.",
  "Seu peão está pensando em mudar de dono.",
  "Aguardando você decidir se vai ser pobre hoje ou amanhã.",
  "Vendo se consigo alugar sua vez para outro jogador mais rápido.",
  "Sua conta bancária é um buraco negro que suga toda a alegria.",
  "Tentando fazer telecinese para mover seu peão para a prisão.",
  "O jogo parou para admirar sua capacidade de perder dinheiro.",
  "Vendo se o banco aceita pagamento em memes.",
  "Aguardando o milagre da multiplicação das suas moedas (spoiler: não vai rolar).",
  "Sua estratégia é andar em círculos e esperar o melhor.",
  "Tentando convencer a carta de 'Saída Livre da Prisão' a não funcionar com você.",
  "O banco está cobrando taxa de inatividade da sua conta.",
  "Limpando o tapete vermelho para a minha vitória.",
  "Seu peão está com depressão pós-jogada.",
  "Aguardando você perceber que o jogo não é de caridade.",
  "Vendo se consigo vender ar engarrafado para você.",
  "Sua sorte foi abduzida por alienígenas.",
  "Tentando hackear o sistema para aumentar o preço dos meus aluguéis.",
  "O tempo está passando e você está ficando mais pobre a cada segundo.",
  "Vendo se o banco aceita pagamento em promessas de campanha política.",
  "Aguardando o momento em que você vai virar a mesa (virtualmente).",
  "Sua jogada é tão previsível que até o algoritmo bocejou.",
  "Tentando fazer o peão de navio afundar no tabuleiro.",
  "O banco avisou que seu score de crédito é negativo.",
  "Limpando a vitrine onde vou expor todo o dinheiro que ganhei de você.",
  "Seu império imobiliário cabe numa caixa de fósforos.",
  "Aguardando você terminar de contar as moedas para pagar o café.",
  "Vendo se consigo hipotecar a sua alma.",
  "Sua conta bancária está pedindo eutanásia.",
  "Tentando convencer o jogo de que 2+2 na sua vez é igual a falência.",
  "O banco está oferecendo um curso de 'Como não ser pobre' para você.",
  "Vendo se o seguro cobre 'jogadas desastrosas'.",
  "Aguardando você perceber que eu sou o dono do tabuleiro e você é só visita.",
  "Sua sorte é igual feriado no domingo: inútil.",
  "Tentando fazer o peão de carro enguiçar na frente do meu hotel.",
  "O tempo cura tudo, menos a sua falta de dinheiro.",
  "Limpando o histórico para ninguém ver o massacre que está sendo esse jogo.",
  "Seu peão está pedindo para ser trocado por um cone de trânsito.",
  "Aguardando você decidir se vai falir com dignidade ou chorando.",
  "Vendo se o banco aceita pagamento em tampinhas de garrafa.",
  "Sua estratégia de jogo foi desenhada por uma criança de 3 anos.",
  "Tentando descobrir onde você esconde o dinheiro (se é que tem).",
  "O banco mandou avisar que a festa acabou para você.",
  "Vendo se consigo vender ingressos para o seu funeral financeiro.",
  "Aguardando a luz no fim do túnel (é o trem vindo te atropelar).",
  "Sua conta bancária está mais vermelha que o hotel em Copacabana.",
  "Tentando fazer o dado cair fora da mesa (virtualmente).",
  "O jogo está pensando se te dá uma chance ou te humilha logo.",
  "Limpando a saliva de tanto rir da sua desgraça.",
  "Seu peão está se sentindo sozinho na casa 'Vá para a Prisão'.",
  "Aguardando você perceber que a vida é dura e o Banco Imobiliário é pior.",
  "Vendo se consigo comprar sua lealdade com um desconto no aluguel.",
  "Sua sorte foi cancelada por falta de pagamento.",
  "Tentando convencer o banco a cobrar juros sobre os juros.",
  "O tempo voa quando a gente está ganhando (eu) e se arrasta quando está perdendo (você).",
  "Vendo se o banco aceita pagamento em abraços virtuais.",
  "Aguardando o momento em que você vai pedir para reiniciar a partida.",
  "Sua estratégia é tão ruim que deveria ser crime.",
  "Tentando fazer o peão de chapéu voar com o vento da sua derrota.",
  "O banco está preparando a papelada da sua concordata.",
  "Limpando o suor frio da sua testa à distância.",
  "Seu império é uma miragem no deserto da sua conta bancária.",
  "Aguardando você sair do cheque especial.",
  "Vendo se consigo vender a Torre Eiffel para você (e nem tem no jogo).",
  "Sua sorte é igual a nota de 3 reais: falsa.",
  "Tentando bloquear sua passagem com uma barreira invisível.",
  "O jogo está perguntando se você quer desistir agora ou passar vergonha depois.",
  "Vendo se o banco aceita pagamento em moedas de chocolate derretidas.",
  "Aguardando a sua reação quando cair na minha propriedade mais cara.",
  "Sua conta bancária é um poema triste.",
  "Tentando fazer o peão de ferro virar sucata.",
  "O banco avisou que seu limite de crédito é R$ 0,00.",
  "Limpando a poeira da sua carteira vazia.",
  "Seu peão está pedindo para sair do jogo.",
  "Aguardando você perceber que não tem escapatória.",
  "Vendo se consigo comprar o seu silêncio eterno no chat.",
  "Sua sorte foi atropelada por um caminhão de azar.",
  "Tentando convencer o sistema a te dar um 'Game Over' antecipado.",
  "O tempo está acabando e sua dívida só aumenta.",
  "Vendo se o banco aceita pagamento em sonhos e esperanças.",
  "Aguardando o colapso total da sua economia pessoal.",
  "Sua estratégia é um barco furado no meio do oceano.",
  "Tentando fazer o peão de cachorro morder o banqueiro.",
  "O banco está rindo da sua tentativa de negociar a dívida.",
  "Limpando o caminho para você ir direto para a sarjeta.",
  "Seu império imobiliário é uma piada pronta.",
  "Aguardando você pedir arrego em 5, 4, 3...",
  "Vendo se consigo hipotecar a sua dignidade.",
  "Sua conta bancária está em estado terminal.",
  "Tentando fazer o dado cair no número que te leva à falência.",
  "O jogo acabou para você, só esqueceram de te avisar.",
  "Vendo se o banco aceita pagamento em lágrimas.",
  "Aguardando a sua queda para eu poder aplaudir.",
  "Sua sorte é inexistente, igual ao seu saldo.",
  "Tentando bloquear sua conta bancária mentalmente.",
  "O banco avisou que você é persona non grata.",
  "Limpando o tabuleiro para a próxima vítima (você já era).",
  "Seu peão está com vergonha de ser seu.",
  "Aguardando o fim do seu sofrimento financeiro.",
  "Vendo se consigo comprar sua alma por um preço camarada.",
  "Sua estratégia é falhar com sucesso.",
  "Tentando convencer o destino a ser cruel com você.",
  "O tempo parou só para ver você perder.",
  "Vendo se o banco aceita pagamento em arrependimentos.",
  "Aguardando a sua falência total e irrestrita.",
  "Sua conta bancária é um deserto árido.",
  "Tentando fazer o peão de navio naufragar.",
  "O banco está preparando o seu atestado de pobreza.",
  "Limpando o chão com a sua reputação de jogador.",
  "Seu império é uma farsa.",
  "Aguardando você entregar os pontos.",
  "Vendo se consigo penhorar o seu futuro.",
  "Sua sorte acabou antes de começar.",
  "Tentando fazer o jogo travar só para você não jogar.",
  "O banco avisou que você está devendo até a alma.",
  "Limpando a sujeira que sobrou do seu dinheiro.",
  "Seu peão desistiu de você.",
  "Aguardando o seu fim trágico no jogo.",
  "Vendo se consigo comprar a sua derrota.",
  "Sua conta bancária morreu.",
];

export const frasesPrisao = [
  // Clássicas de Prisão
  "Contando os azulejos da parede... 4.302, 4.303...",
  "O sol nasce quadrado, mas o aluguel é 0800.",
  "Tentando cavar um túnel com uma colher de plástico.",
  "Fazendo amizade com um rato chamado Genésio.",
  "A comida aqui tem gosto de papelão molhado.",
  "Alguém tem um bolo com uma lima dentro aí?",
  "Treinando para o campeonato mundial de encarar a parede.",
  "Troco proteção por uma carta de 'Saída Livre'.",
  "A cama é dura, mas a consciência é... pesada também.",
  "Limpando o chão com uma escova de dentes.",
  "Escrevendo minhas memórias no papel higiênico.",
  "O uniforme laranja não valoriza meu tom de pele.",
  "Serrando as grades com fio dental. Progresso: 0.1%.",
  "Fui preso por ser bonito demais (mentira, foi o dado).",
  "O guarda confiscou meus dados da sorte.",

  // Arrependimento e Dinheiro
  "Deveria ter contratado um advogado melhor.",
  "O crime compensa? Meu saldo bancário diz que não.",
  "Só queria passar no Início e pegar meu salário...",
  "Refletindo sobre minhas escolhas financeiras duvidosas.",
  "Enquanto eu tô aqui, alguém tá comprando meus terrenos.",
  "Economizando dinheiro à força.",
  "Pelo menos aqui dentro não pago Imposto de Renda.",
  "Minha mãe avisou para não andar com más companhias.",
  "Planejando meu retorno triunfal (e falido).",
  "Esperando o habeas corpus ou um milagre financeiro.",

  // Mecânica do Jogo / Meta
  "Esperando aquele 5 duplo salvador.",
  "A culpa foi do dado, eu juro!",
  "Vendo os outros jogadores se divertindo através das grades.",
  "Isso é injustiça! Eu exijo uma recontagem dos passos.",
  "Pule a vez. Pule a esperança.",
  "O jogo continua lá fora... sem mim.",
  "Alguém me empresta 50 reais pra fiança?",
  "Será que se eu ficar muito tempo parado o jogo trava?",
  "Pausa para o café (forçado).",
  "Assistindo sua falência de camarote.",

  // Absurdas e Aleatórias
  "Avisem minha família que vou me atrasar para o jantar.",
  "Tentando subornar o guarda com dinheiro do Banco Imobiliário.",
  "Jurando inocência... ninguém acredita.",
  "Meditando para não virar a mesa do jogo.",
  "Fazendo tatuagem de chiclete no braço.",
  "Discutindo filosofia com a parede.",
  "Organizando uma rebelião de um homem só.",
  "O Wi-Fi aqui da cela é péssimo.",
  "Cadê o Michael Scofield quando a gente precisa?",
  "Dormindo para o tempo passar mais rápido.",
  "Procura-se: Companheiro de cela que não ronque.",
  "Aproveite para ir ao banheiro na vida real.",
  "Carregando liberdade... (50%)",
  "Error 404: Lawyer Not Found.",
  "Se eu sair daqui, eu compro esse presídio e demito todo mundo!",
];

export const frasesEstacionamento = [
  "Aproveite, é a única coisa grátis que você vai ver hoje.",
  "Verificando se caiu alguma moeda debaixo do banco do motorista.",
  "Discutindo com o flanelinha que insiste em cobrar 'uma trocado'.",
  "O único lugar do tabuleiro onde o capitalismo te dá uma folga.",
  "Ajustando o retrovisor para ver seus oponentes falindo lá atrás.",
  "Aproveitando o Wi-Fi grátis do estacionamento para ver memes.",
  "Dormindo no volante enquanto a polícia não vem.",
  "Limpando o para-brisa com jornal velho para economizar.",
  "Isso aqui não é banco, não espere ganhar dinheiro parado.",
  "A única vaga da cidade que não cobra Zona Azul.",
  "Sentindo o cheiro de asfalto quente e liberdade financeira.",
  "Fingindo que o carro quebrou só para não pagar aluguel na próxima casa.",
  "Calibrando os pneus para fugir da prisão mais tarde.",
  "Aqui você não paga, mas também não ganha. A vida é assim.",
  "Contando os pombos que estão mirando no seu teto solar.",
  "Olhando o óleo, a água e a conta bancária (que está vazia).",
  "Aquele momento de paz antes de cair no hotel do adversário.",
  "Estacionou tão mal que ocupou duas casas do tabuleiro.",
  "Procurando o ticket do estacionamento que você perdeu.",
  "Dando aquela espreguiçada enquanto os outros se matam por dinheiro.",
  "Aproveite a sombra, porque o sol da falência vem aí.",
  "Verificando se o seguro cobre tédio no estacionamento.",
  "O único lugar seguro de um mundo cruel e mercenário.",
  "Dando uma polida na lataria do peão.",
  "Esperando o motor esfriar e a sorte esquentar.",
  "Seu carro foi confundido com Uber, recuse a corrida.",
  "Ouvindo rádio AM enquanto espera sua vez de sofrer.",
  "Troca de óleo grátis? Não, é só estacionamento mesmo.",
  "Aqui a única taxa é a de paciência.",
  "Fazendo baliza no meio do caos imobiliário.",
  "Escondendo o carro para o oficial de justiça não ver.",
  "Aproveitando para comer um lanche que trouxe de casa.",
  "Sintonizando a estação 'Felicidade' (fora do ar).",
  "O único lugar onde você não é assaltado pelo banco.",
  "Vendo se tem risco na pintura (foi o peão do cachorro).",
  "Aproveitando o silêncio antes da tempestade de boletos.",
  "Dando ré na vida para ver se conserta o passado.",
  "Estacionamento grátis: o oásis do pobre.",
  "Fingindo que está morto para não pagar o IPVA.",
  "Procurando moedas no cinzeiro do carro.",
  "A única coisa que cresce aqui é a sua vontade de ganhar.",
  "Nem tente lavar o carro, vai chover na próxima rodada.",
  "Aqui você é rei, lá fora você é só mais um devedor.",
  "Descansando a beleza e a carteira.",
  "O freio de mão puxado e a conta no vermelho.",
  "Olhando o mapa para ver onde foi que eu errei na vida.",
  "Aproveitando para tirar um cochilo no banco de trás.",
  "Estacionou na vaga de idoso? O banco está de olho.",
  "Aqui ninguém te cobra, nem a sua consciência.",
  "O único lugar onde o aluguel é R$ 0,00. Um sonho.",
  "Verificando se o estepe ainda está lá ou se o banco levou.",
  "Colocando a playlist 'Músicas para não Falir' no talo.",
  "Aproveitando para chorar no volante sem ninguém ver.",
  "Aqui é seguro... até você ter que rolar os dados de novo.",
  "Onde os fracos não têm vez, mas têm vaga.",
  "Sentado no capô olhando as estrelas (e o saldo negativo).",
  "A única multa aqui é por excesso de lerdeza.",
  "Fingindo que está esperando alguém, mas só está sem grana.",
  "Aproveitando para atualizar o GPS da vitória.",
  "Limpando o tapete do carro, que tem mais terra que seus terrenos.",
  "Aqui o 'sem parar' é literal: você parou mesmo.",
  "Vendo se o ar-condicionado gasta muito combustível virtual.",
  "Aproveitando para responder as mensagens do agiota.",
  "Aqui você não perde dinheiro, só perde tempo.",
  "O lugar perfeito para repensar suas escolhas de vida.",
  "Estacionamento rotativo: sua sorte roda e você fica.",
  "Vendo se o guardador de carros aceita um sorriso como pagamento.",
  "Aqui o guincho não te pega (por enquanto).",
  "Aproveitando a brisa de não dever nada a ninguém por um turno.",
  "O único quadrado do tabuleiro sem cobrador na porta.",
  "Verificando se trancou o carro (o peão do ladrão está solto).",
  "Aqui é 'Free Parking', não 'Free Money'. Pode chorar.",
  "Aproveitando para fazer uma revisão nos freios da economia.",
  "Onde os cansados descansam e os falidos se escondem.",
  "Estacionado na vaga da esperança.",
  "Aproveitando para limpar o porta-malas cheio de dívidas.",
  "Aqui você é livre... por enquanto.",
  "O único lugar onde o leão do imposto de renda não morde.",
  "Vendo se o rádio pega alguma estação que não toque sertanejo universitário.",
  "Aproveitando para contar as moedas do console.",
  "Aqui você não paga, mas a angústia é cortesia da casa.",
  "Estacionamento VIP para jogadores quase falidos.",
  "Onde o filho chora e a mãe não vê (porque o vidro é fumê).",
  "Aproveitando para dar uma geral na bagunça do banco de trás.",
  "Aqui o silêncio vale ouro (literalmente, você não gasta).",
  "Estacionado na contramão do sucesso.",
  "O único lugar onde 'parar' é uma boa estratégia.",
  "Aproveitando para ver se o pneu careca aguenta mais uma rodada.",
  "Aqui você não precisa dar gorjeta, só dar passagem.",
  "Estacionamento: o purgatório do Banco Imobiliário.",
  "Aproveitando para meditar sobre a futilidade do dinheiro.",
  "Aqui você está seguro, lá fora é selva.",
  "Vendo se o motor está vazando óleo ou se é só minha dignidade.",
  "Aproveitando para retocar a maquiagem da derrota.",
  "Aqui o tempo para, mas os juros continuam correndo.",
  "Estacionado entre a cruz e a espada.",
  "Aproveitando para ler o jornal de ontem que estava no banco.",
  "Aqui você é invisível para os credores.",
  "Vendo se a bateria arriou ou se foi meu ânimo.",
  "Aproveitando para comer aquela bala que estava no porta-luvas há 3 anos.",
  "Aproveitando para contar os fiapos no carpete do carro.",
  "Aqui o único risco é morrer de tédio.",
  "Estacionado na sombra enquanto o circo pega fogo lá fora.",
  "Verificando se o macaco do carro serve para levantar minha autoestima.",
  "O único quadrado onde o capitalismo esqueceu de você.",
  "Dando aquela conferida se tranquei a porta de casa (mentalmente).",
  "Aproveitando para ler a validade do extintor de incêndio.",
  "Aqui você não ganha, mas pelo menos não perde a camisa.",
  "Fingindo que estou dormindo para o guardinha não pedir gorjeta.",
  "Aproveitando para desenhar na poeira do painel.",
  "Onde o filho chora e a mãe não ouve porque o som tá alto.",
  "Aqui a inflação não chega (espero).",
  "Estacionado em vaga preferencial para 'Falidos e Cansados'.",
  "Aproveitando para organizar as moedas por tamanho e cor.",
  "Olhando para o teto solar e questionando minhas escolhas de vida.",
  "Aqui o tempo é relativo: parece que parou, mas a dívida corre.",
  "A única coisa que você vai levar daqui é poeira nos pneus.",
  "Aproveitando para limpar o histórico do GPS.",
  "Estacionado na divisa entre a pobreza e a miséria.",
  "Aqui o banco não te acha, é o ponto cego do sistema.",
  "Aproveitando para ensaiar o discurso de vitória (ou de falência).",
  "Vendo se o limpador de para-brisa funciona a seco.",
  "Aqui você é apenas um carro parado num mundo em movimento.",
  "Aproveitando para tirar a pedra que entrou no sapato.",
  "Estacionado na vaga de quem desistiu de entender a economia.",
  "Aqui não tem juros, mas também não tem diversão.",
  "Aproveitando para ver se o cinto de segurança ainda serve.",
  "O único lugar onde você não precisa vender um rim.",
  "Fingindo que o carro enguiçou para ganhar tempo.",
  "Aproveitando para ler as letras miúdas do seguro.",
  "Aqui você está protegido contra tubarões imobiliários.",
  "Estacionado na zona neutra da guerra financeira.",
  "Aproveitando para contar quantos postes tem na rua.",
  "Aqui o silêncio é constrangedor, igual ao seu saldo.",
  "Vendo se consigo sintonizar a rádio da prosperidade.",
  "Aproveitando para limpar o óculos na camisa.",
  "Estacionado longe do meio-fio para não arranhar a calota.",
  "Aqui você é livre para não fazer absolutamente nada.",
  "Aproveitando para ver se a luz do teto acende.",
  "O único lugar onde a ganância tira um cochilo.",
  "Estacionado na vaga reservada para 'Quase Bilionários'.",
  "Aproveitando para ver se o tapete do carro está alinhado.",
  "Aqui não tem taxa de conveniência, só de paciência.",
  "Vendo se o porta-luvas tem algum tesouro escondido (só tem papel).",
  "Aproveitando para respirar sem ser taxado.",
  "Estacionado na contramão da lógica.",
  "Aqui você não é um número, é só um obstáculo.",
  "Aproveitando para ver se o freio de mão está bem puxado.",
  "O único lugar onde você não precisa hipotecar o sorriso.",
  "Estacionado na sombra da dúvida.",
  "Aproveitando para ver se o banco do passageiro reclina.",
  "Aqui o leão do imposto de renda vira um gatinho.",
  "Vendo se o espelho retrovisor reflete um vencedor.",
  "Aproveitando para tirar o pó do volante.",
  "Estacionado na vaga de quem espera um milagre.",
  "Aqui você não precisa dar satisfação para o gerente.",
  "Aproveitando para ver se a buzina ainda funciona (melhor não).",
  "O único lugar onde a crise dá uma trégua.",
  "Estacionado na beira do abismo financeiro, mas com o freio puxado.",
  "Aproveitando para ver se o teto do carro precisa de pintura.",
  "Aqui você é dono do seu tempo (que não vale nada).",
  "Vendo se o cheirinho de 'Carro Novo' venceu em 1999.",
  "Aproveitando para ver se o cinto de segurança aperta a barriga.",
  "Estacionado na vaga de quem não tem pressa de perder dinheiro.",
  "Aqui o mundo gira, mas você fica.",
  "Aproveitando para ver se a porta fecha com um clique suave.",
  "O único lugar onde você não é julgado pelo saldo.",
  "Estacionado na vaga da imunidade temporária.",
  "Aproveitando para ver se o vidro sobe até o fim.",
  "Aqui você pode sonhar alto (desde que não custe nada).",
  "Vendo se o painel acende luzes que eu não conhecia.",
  "Aproveitando para ver se o pedal do acelerador está macio.",
  "Estacionado na vaga de quem está 'só olhando'.",
  "Aqui você não precisa de fiador.",
  "Aproveitando para ver se o porta-malas cabe toda a minha frustração.",
  "O único lugar onde você não precisa assinar nada.",
  "Estacionado na vaga de quem esqueceu a carteira.",
  "Aproveitando para ver se o rádio pega AM.",
  "Aqui você é invisível para as cobranças.",
  "Vendo se o banco de trás tem espaço para as pernas.",
  "Aproveitando para ver se o volante tem folga.",
  "Estacionado na vaga de quem está esperando o salário cair.",
  "Aqui não tem meta de vendas.",
  "Aproveitando para ver se o ar-condicionado gela ou só faz barulho.",
  "O único lugar onde você não precisa de gravata.",
  "Estacionado na vaga de quem está fugindo dos parentes.",
  "Aproveitando para ver se o pisca-alerta funciona.",
  "Aqui você não precisa de senha.",
  "Vendo se o capô está quente (igual minha cabeça).",
  "Aproveitando para ver se a placa do carro ainda está lá.",
  "Estacionado na vaga de quem não tem para onde ir.",
  "Aqui não tem taxa de serviço.",
  "Aproveitando para ver se o pneu estepe está cheio.",
  "O único lugar onde você não precisa de cartão de crédito.",
  "Estacionado na vaga de quem está pensando na vida.",
  "Aproveitando para ver se o farol está alinhado.",
  "Aqui você não precisa de comprovante de residência.",
  "Vendo se o escapamento está soltando fumaça.",
  "Aproveitando para ver se a calota está firme."
];

export const frasesImpostoRenda = [
  "O Leão rugiu e seu saldo sumiu.",
  "Caiu na malha fina do tabuleiro.",
  "O governo agradece sua doação involuntária.",
  "Declarou esse terreno na ficha 34-B? Acho que não.",
  "Sua sonegação falhou com sucesso.",
  "CPF na nota? Não adianta, vai pagar do mesmo jeito.",
  "Contribuição compulsória para o churrasco dos políticos.",
  "Você trabalhou, você lucrou, o governo levou.",
  "A Receita Federal curtiu sua foto ostentando e veio cobrar.",
  "Isso não é um assalto, é apenas 'redistribuição tributária'.",
  "Esqueceu de declarar o dinheiro que ganhou no aniversário?",
  "O Leão não é vegano, ele come o seu salário.",
  "Pague sorrindo para não chorar.",
  "Seu contador fugiu para o México, pague a multa.",
  "Taxa de existência: você respira, você paga.",
  "O sistema detectou excesso de felicidade, pague imposto.",
  "Isso vai doer mais em mim do que em... mentira, vai doer em você.",
  "O Leão sentiu cheiro de dinheiro novo na sua conta.",
  "Hora de financiar as obras que nunca ficam prontas.",
  "Você caiu na casa favorita do governo.",
  "Seu imposto de renda retido na fonte da tristeza.",
  "Auditoria surpresa! E você foi o sorteado.",
  "O Leão mordeu, e ele não escova os dentes.",
  "Pague agora, reclame nunca.",
  "Sua isenção foi revogada por motivo de: porque sim.",
  "A mordida do Leão é mais forte que a sua vontade de vencer.",
  "Você não leu as letras miúdas da constituição do jogo?",
  "Dinheiro na mão é vendaval, dinheiro no imposto é tchau.",
  "O Leão está de dieta, mas abriu uma exceção para você.",
  "A alíquota subiu enquanto você lia essa frase.",
  "Pague o imposto ou vá direto para a prisão (sem passar pelo início).",
  "O governo viu você comprando aquele hotel e ficou com inveja.",
  "Imposto sobre Grandes Fortunas (ou sobre o pouco que você tem).",
  "Você foi taxado por excesso de lerdeza na rodada anterior.",
  "A Receita Federal mandou um abraço e um boleto.",
  "O Leão não dorme, ele só espera você passar.",
  "Pague o DARF sem chorar.",
  "Sua restituição foi negada para sempre.",
  "Imposto sobre movimentação de peão no tabuleiro.",
  "O Leão te pegou na curva da estrada.",
  "Pague o dízimo do governo.",
  "Sua declaração caiu em exigência. A exigência é: pague tudo.",
  "O Leão disse que seu dinheiro tem um gosto ótimo.",
  "Taxa de renovação do seu CPF no jogo.",
  "Você tentou esconder, mas o Leão tem faro fino.",
  "O governo precisa trocar a frota de carros, colabore.",
  "Imposto sobre a lágrima que acabou de cair do seu olho.",
  "Seu leão de estimação cresceu e quer comer sua carteira.",
  "A mordida foi profunda, vai precisar de pontos (na conta).",
  "Pague o imposto e ganhe um recibo de 'Trouxa do Ano'.",
  "O Leão te viu sorrindo e decidiu cobrar taxa de alegria.",
  "Sua sonegação fiscal foi detectada pelo satélite.",
  "Contribuição para o fundo de aposentadoria dos dados.",
  "Você esqueceu de declarar aquele dinheiro que achou no chão.",
  "O governo precisa reformar a casa de verão do ministro, pague.",
  "Imposto sobre a esperança de vencer o jogo.",
  "A Receita Federal não aceita 'dinheiro de mentirinha' como desculpa.",
  "Você pisou num pixel que pertence ao Estado.",
  "Taxa de iluminação pública do tabuleiro (está cara).",
  "O Leão achou seu esconderijo de notas de 500.",
  "Multa por excesso de sorte nas rodadas anteriores.",
  "Seu CPF foi sorteado para pagar a conta do jantar do congresso.",
  "Declaração retificadora: você deve tudo o que tem.",
  "Imposto sobre ocupação de espaço virtual.",
  "O governo decidiu que 15% do seu suor pertence a ele.",
  "Caiu na malha fina por declarar 'bonito' como profissão.",
  "Pague o imposto ou seu peão será deportado.",
  "Taxa de preservação da sua liberdade (por enquanto).",
  "O Leão não quer saber se você tem família, ele quer o dinheiro.",
  "Seu contador te vendeu para a Receita, pague a fiança.",
  "Imposto sobre grandes fortunas imaginárias.",
  "Você respirou fundo? Isso tem taxa.",
  "O governo estatizou parte da sua carteira.",
  "Contribuição para o sindicato dos banqueiros.",
  "Você parece próspero, isso ofende o Leão. Pague.",
  "Taxa de licenciamento do seu peão para andar no tabuleiro.",
  "O Leão disse que sua carne é dura, prefere seu dinheiro.",
  "Imposto retroativo de 1920 que esqueceram de cobrar.",
  "Você tentou lavar dinheiro na máquina de lavar? Pague a multa.",
  "Taxa de manutenção da burocracia nacional.",
  "O Leão está juntando dinheiro para um implante de juba.",
  "Sua isenção fiscal venceu há 3 segundos.",
  "Pague agora para não ter seus bens leiloados amanhã.",
  "Imposto sobre o uso de sapatos de marca no tabuleiro.",
  "O governo viu você comprando casas e quer a parte dele.",
  "Taxa de limpeza da sua consciência fiscal.",
  "O Leão te abraçou... e levou sua carteira.",
  "Multa por atraso no pagamento de uma conta que você nem sabia que tinha.",
  "Imposto sobre movimentação financeira suspeita (você ganhou muito rápido).",
  "O governo decretou feriado bancário, mas o débito funciona.",
  "Taxa de emissão de boleto para cobrar outra taxa.",
  "Você foi taxado por ser um cidadão exemplar (ou não).",
  "O Leão mordeu seu calcanhar e seu saldo.",
  "Imposto de Renda: a única certeza além da morte e da falência.",
  "Sua declaração de bens estava incompleta, faltou a sua dignidade.",
  "Taxa de 'quem mandou nascer nesse país'.",
  "O governo precisa de troco, passe tudo o que tem.",
  "Imposto sobre o brilho do seu olhar ganancioso.",
  "O Leão está fazendo dieta low-carb, só come notas altas.",
  "Você caiu na casa do Leão. Não corra, é pior."
];

export const frasesTaxaRiqueza = [
  "Ser rico custa caro, sabia?",
  "Taxa de ostentação: pague por brilhar demais.",
  "O preço do caviar subiu, sinto muito.",
  "Quem mandou querer ter anel de diamante?",
  "Imposto sobre excesso de carisma e dinheiro.",
  "Sua vida de marajá acabou de ficar mais cara.",
  "Taxa de manutenção do seu iate imaginário.",
  "Você tem muito dinheiro, vamos aliviar esse peso.",
  "O clube de golfe aumentou a mensalidade.",
  "Seus sapatos de couro italiano precisam de graxa importada.",
  "Taxa de inveja alheia: pague por ser o melhor.",
  "O champanhe estava quente, pague a multa de etiqueta.",
  "Seu monóculo de ouro caiu e quebrou.",
  "Taxa de limpeza da sua piscina de dinheiro.",
  "Problemas de gente rica: ter que pagar taxas de gente rica.",
  "O mordomo pediu aumento e o sindicato apoiou.",
  "Você ostentou demais no Instagram do jogo.",
  "Taxa de polimento das suas barras de ouro.",
  "Sua limusine foi multada por excesso de comprimento.",
  "O preço da fama (e da fortuna) chegou.",
  "Taxa de solidariedade forçada com o banco.",
  "Você comprou um terno de seda e rasgou na primeira usada.",
  "Taxa de 'bon vivant'.",
  "Seu cavalo de raça precisa de ferraduras de platina.",
  "Você quis ser VIP, agora pague o preço do camarote.",
  "Imposto sobre propriedades com vista para o mar.",
  "Sua obra de arte acabou de desvalorizar, compense a perda.",
  "Taxa de estacionamento do seu jatinho particular.",
  "Você foi taxado por ser chique demais para esse tabuleiro.",
  "O banco acha que você tem dinheiro demais guardado.",
  "Taxa de excesso de bagagem na sua conta bancária.",
  "Sua festa de gala deu prejuízo.",
  "O lustre de cristal da sua mansão caiu.",
  "Taxa de beleza financeira (você é lindo, pague).",
  "Seu personal trainer financeiro cobrou a consulta.",
  "Você contratou um chef francês e ele queimou o suflê.",
  "Taxa de exclusividade: só você paga isso hoje.",
  "Seu relógio suíço atrasou, pague a manutenção.",
  "Imposto sobre o uso de perfumes importados.",
  "Sua roupa de grife saiu de moda, pague a multa fashion.",
  "Taxa de engomadoria das suas notas de dinheiro.",
  "Você foi pego bebendo água mineral dos Alpes, pague.",
  "O seguro da sua Ferrari venceu hoje.",
  "Taxa de filiação ao clube dos milionários falidos.",
  "Seu tapete persa precisa de lavagem a seco.",
  "Você comprou uma ilha e esqueceu de pagar o IPTU dela.",
  "Taxa de arrogância imobiliária.",
  "Seu vinho de 1950 virou vinagre.",
  "O banco decidiu que você é rico demais para não pagar nada.",
  "Taxa de 'quem pode, pode; quem não pode, se sacode'.",
  "O caviar beluga aumentou, pague a diferença.",
  "Taxa de aterrissagem do seu helicóptero no jardim.",
  "Seu mordomo está exigindo adicional noturno.",
  "Manutenção da sua coleção de vinhos raros.",
  "Você contratou um DJ famoso para tocar na sua sala, pague.",
  "Taxa de limpeza das suas obras de arte renascentistas.",
  "Seu cavalo de polo precisa de fisioterapia.",
  "O clube de campo exige a troca dos tacos de golfe por ouro.",
  "Imposto sobre excesso de elegância.",
  "Sua limusine arranhou o para-choque de diamante, conserte.",
  "Taxa de renovação do seu título de nobreza.",
  "Você comprou uma estrela e ela precisa de manutenção.",
  "Seu personal stylist cobrou hora extra.",
  "Taxa de engarrafamento do seu vinho exclusivo.",
  "O seguro da sua tiara de diamantes venceu.",
  "Você mandou buscar água na geleira da Patagônia, pague o frete.",
  "Taxa de 'bonito e rico'.",
  "Sua ilha particular precisa de areia nova importada.",
  "O chef particular queimou o foie gras, compre outro.",
  "Taxa de blindagem do seu terno de grife.",
  "Você alugou o Louvre para uma festa, pague o aluguel.",
  "Imposto sobre posse de animais exóticos (seu tigre de estimação).",
  "Taxa de alfaiataria: suas roupas não podem ter rugas.",
  "O spa do seu cachorro precisa de sais de banho.",
  "Você comprou um fóssil de dinossauro ilegal, pague a propina.",
  "Taxa de exclusividade do ar que você respira na cobertura.",
  "Seu piano de cauda desafinou, chame o técnico europeu.",
  "Imposto sobre uso de talheres de prata no café da manhã.",
  "Sua piscina de borda infinita vazou no vizinho.",
  "Taxa de aquecimento do piso do seu banheiro.",
  "Você contratou um poeta para escrever sua biografia, pague.",
  "O piloto do seu jato quer aumento.",
  "Taxa de importação das suas trufas brancas.",
  "Você exagerou no leilão de arte, cubra o lance.",
  "Imposto sobre ter o nome em prédios importantes.",
  "Sua adega climatizada pifou, salve os vinhos.",
  "Taxa de filiação ao clube dos 'Donos do Mundo'.",
  "Você mandou banhar seu carro a ouro, pague o ourives.",
  "Imposto sobre o uso de palavras difíceis e cultas.",
  "Sua estatua de cera no museu derreteu, pague a restauração.",
  "Taxa de manutenção do seu sorriso perfeito.",
  "Você comprou um time de futebol e eles perderam, pague a multa.",
  "Imposto sobre excesso de zeros na conta.",
  "Sua cobertura triplex precisa de vidros à prova de pobres.",
  "Taxa de degustação de queijos que você nem consegue pronunciar.",
  "Você contratou uma orquestra para te acordar, pague os músicos.",
  "Imposto sobre a inveja que você causa nos outros jogadores.",
  "Sua assinatura da revista 'Bilionários Anônimos' venceu.",
  "Taxa de polimento do seu ego.",
  "Você é rico demais para reclamar, apenas pague."
];
