export const frasesDeEspera = [
  "Contando o dinheiro dos outros em pensamento...",
  "Planejando como cobrar aluguel até pelo ar que você respira.",
  "Limpando as notas de R$ 500 para parecerem mais novas.",
  "Escondendo patrimônio antes que o Leão da Receita veja.",
  "Ajustando o preço do aluguel de acordo com o meu humor.",
  "Consultando meu advogado para saber se posso te expulsar.",
  "Subornando o banco para ignorar suas propriedades...",
  "Pedindo um empréstimo que nunca pretendo pagar.",
  "Rezando para você cair na prisão sem passar pelo Início.",
  "Limpando a poeira dos meus hotéis de luxo.", 
  "Verificando se as notas de papel são laváveis na máquina.",
  "Enquanto você demora, a inflação come o seu lucro.",
  "Aguardando minha vez de te levar à falência.",
  "Se demorar mais, vou começar a cobrar estadia nesta tela.",
  "O café já esfriou e o seu império ainda não saiu do lugar.",
  "Assistindo sua dignidade financeira sumir aos poucos.",
  "Treinando meu vira-lata para morder o seu peão.",
  "Tentando convencer o sistema que erro do banco é eterno.",
  "Instalando câmeras escondidas na Avenida Paulista.",
  "Contratando um fantasma para assombrar seus terrenos.",
  "Sabia que a paciência é uma virtude que não paga aluguel?",
  "O banco está considerando cobrar taxa por este tempo de espera.",
  "Já deu tempo de construir um hotel e declarar falência.",
  "Seu oponente está consultando um oráculo para a próxima jogada.",
  "Embaralhando as cartas de sorte para eu tirar as melhores.",
  "Verificando se há moedas perdidas debaixo do tabuleiro.",
  "Polindo os dados para saírem números maiores.",
  "Sua sorte está sendo processada por falta de provas.",
  "Calculando quanto de gorjeta devo dar ao banco hoje.",
  "Esperando que o seu peão tropece num buraco no caminho.",
  "Dando banho nos porquinhos de barro onde guardo as moedas.",
  "Avisando os vizinhos que o seu império vai cair hoje.",
  "Pensando se devo comprar sua casa ou o seu silêncio.",
  "O mercado financeiro parou para ver sua indecisão.",
  "Os dados estão fazendo aquecimento na academia.",
  "Planejando uma festa na minha mansão e você não está convidado.",
  "O gerente do banco foi lanchar, tente não falir agora.",
  "Lendo as letras miúdas do contrato que você não leu.",
  "Vendo se a hipoteca do seu peão ainda está ativa.",
  "Contratando um detetive para seguir o seu dinheiro.",
  "Dando corda nos dados para eles correrem mais rápido.",
  "O tabuleiro está ficando com sono da sua demora.",
  "Medindo a distância entre a sua peça e a falência.",
  "Verificando se o banco aceita pagamento em barras de chocolate.",
  "O seu saldo está rindo de você neste momento.",
  "Tentando subornar o juiz do jogo com uma nota de R$ 1.",
  "Vendo se consigo vender este tempo de espera como propaganda.",
  "Os hotéis estão sendo pintados enquanto você pensa.",
  "Conferindo se a prisão tem Wi-Fi para quando você chegar.",
  "Sua jogada está perdida no correio, por favor aguarde.",
  "Fazendo amizade com os dados para eles não me traírem.",
  "Planejando um golpe de estado no banco central do jogo.",
  "Aguardando que a gravidade decida onde os dados caem.",
  "O seu império imobiliário parece um castelo de cartas.",
  "Vendo se o seguro cobre danos causados por adversários lentos.",
  "Dando um brilho extra no meu peão para te ofuscar.",
  "Seu oponente está lendo o manual de instruções (finalmente).",
  "Verificando se o banco aceita troca por fotos de gatinhos.",
  "O tempo voa, mas o seu peão parece ter criado raízes.",
  "Planejando como gastar o dinheiro que vou te tirar.",
  "Vendo se consigo comprar o silêncio dos dados.",
  "Sua sorte foi viajar e esqueceu de avisar.",
  "Contando quantas vezes você olhou para o meu dinheiro.",
  "Os inquilinos estão fazendo greve pela sua demora.",
  "Polindo as casas verdes para ficarem mais bonitas.",
  "Vendo se encontro petróleo debaixo do meu terreno mais barato.",
  "O seu peão está pedindo 'por favor' para se mexer.",
  "Calculando o juro por cada segundo que você não joga.",
  "Tentando ler a mente do seu adversário (está vazia).",
  "Vendo se consigo hipotecar minha paciência.",
  "Seu destino está sendo escrito por um estagiário do azar.",
  "Aguardando que os astros alinhem sua falência.",
  "Vendo se as cartas de revés têm erro de impressão.",
  "O banco enviou uma carta perguntando se você ainda está vivo.",
  "Dando banho no gnomo da sorte para ver se ele ajuda.",
  "Verificando se o tabuleiro tem inclinação para o meu lado.",
  "Seu oponente está fazendo as contas nos dedos.",
  "Vendo se consigo vender esta tela de espera no OLX.",
  "Os dados estão decidindo quem eles odeiam mais hoje.",
  "Aguardando que a inflação torne meus terrenos caros.",
  "Vendo se a Receita Federal aceita pagamento em rodadas.",
  "O seu peão está planejando uma fuga do tabuleiro.",
  "Vendo se consigo comprar o banco enquanto você não olha.",
  "Aguardando que o universo conspire a meu favor.",
  "Conferindo se o manual permite 'pestar' notas de R$ 10.",
  "Vendo se o seu peão precisa de óleo para se mexer.",
  "O tempo está passando e o aluguel só aumenta.",
  "Vendo se consigo trocar minha sorte por um hambúrguer.",
  "Seu adversário está tentando hipnotizar os dados.",
  "Conferindo se o banco aceita moedas de chocolate.",
  "Vendo se consigo esconder uma nota de R$ 500 na manga.",
  "Aguardando que sua ganância supere sua lógica.",
  "Vendo se o tabuleiro tem garantia contra jogadores lentos.",
  "Os dados estão dormindo, tente não acordá-los agora.",
  "Calculando quanto de imposto vou pagar pela sua derrota.",
  "Vendo se consigo vender sua alma ao banco por um hotel.",
  "O seu destino está em espera, por favor não desligue.",
  "Vendo se encontro uma carta de sorte caída no chão.",
  "Aguardando o eclipse total da sua conta bancária.",
  "O jogo está carregando seu próximo erro estratégico.",
  "Seu oponente está calculando como te levar à falência em 3 idiomas.",
  "Vendo se o banco aceita sua alma como garantia de empréstimo.",
  "Dando risada do seu saldo bancário em silêncio...",
  "O tabuleiro perguntou se você desistiu ou se é só lentidão mesmo.",
  "Contratando um advogado para provar que esse seu dado viciado é crime.",
  "Aguardando o milagre que vai salvar sua conta bancária hoje.",
  "Vendo se consigo trocar seu peão por uma coxinha e um refresco.",
  "O banco avisou: sua dignidade financeira acaba de ser bloqueada.",
  "Contando quantos segundos faltam para você chorar no meu ombro.",
  "Ajustando a taxa de aluguel conforme o tamanho do seu desespero.",
  "Planejando gastar seu dinheiro com coisas inúteis e caras.",
  "Sua estratégia é tão boa que até os dados estão rindo.",
  "Vendo se encontro um chip de inteligência para te emprestar.",
  "O mercado imobiliário parou para ver esse show de horror que você chama de jogada.",
  "Limpando o chão por onde você vai passar... de joelhos e falido.",
  "Aguardando a sua vez enquanto a minha barba cresce 2 centímetros.",
  "Seu império parece um puxadinho feito de palito de picolé.",
  "Vendo se o seguro cobre danos morais causados pela sua demora.",
  "Os hotéis estão prontos para receber seu dinheiro, não demore!",
  "Sua sorte foi comprar cigarro em 1998 e nunca mais voltou.",
  "Avisando ao banco que você é um risco imobiliário nível alto.",
  "Calculando quanto de gorjeta vou dar para os garis limparem seus restos no tabuleiro.",
  "O universo está em choque com a sua falta de visão econômica.",
  "Vendo se consigo hipotecar seu bom senso, já que dinheiro você não tem.",
  "Dando corda na sua paciência antes que ela estoure.",
  "Sua jogada é tão lenta que o sistema entrou em modo de hibernação.",
  "Contratando um palhaço para te animar quando você perder tudo.",
  "Aguardando que a sua única célula cerebral decida o que fazer.",
  "O banco está pensando em cobrar aluguel por esse tempo que você ocupa no servidor.",
  "Vendo se consigo trocar sua foto de perfil por uma de 'Procurado' por dívidas.",
  "Sua conta bancária está em coma profundo e sem previsão de alta.",
  "Contando quantas vezes você respira por minuto para cobrar taxa de oxigênio.",
  "Aguardando que a sua ganância encontre o caminho de volta para a lógica.",
  "Seus terrenos são tão ruins que nem o lixeiro quer passar na frente.",
  "Vendo se o banco aceita pagamento em desculpas esfarrapadas.",
  "Seu oponente já comprou uma ilha com o dinheiro que você ainda nem ganhou.",
  "Aguardando que você perceba que já perdeu, só esqueceu de cair.",
  "O tabuleiro está bocejando... e os dados também.",
  "Vendo se consigo transformar sua dívida numa obra de arte moderna.",
  "Seu futuro imobiliário é tão brilhante quanto um quarto escuro.",
  "Aguardando o momento em que você vai admitir que eu sou o dono do jogo.",
  "Sua vez demora tanto que eu já mudei de religião duas vezes.",
  "Calculando o imposto sobre a sua teimosia.",
  "Vendo se consigo comprar sua propriedade com um vale-transporte usado.",
  "Seu império está sendo leiloado no mercado negro por 2 centavos.",
  "Aguardando você decidir se joga ou se abre um asilo de peões.",
  "O banco me ligou dizendo que você é o 'cliente do mês' na categoria calote.",
  "Vendo se consigo automatizar sua falência para economizar tempo.",
  "Sua sorte é como sinal de Wi-Fi no meio do mato: inexistente.",
  "Aguardando o eclipse da sua inteligência financeira.",
  "Vendo se o banco aceita dente de leite como garantia hipotecária.",
  "Sua estratégia é baseada em 'choro e ranger de dentes'.",
  "O sistema está tentando entender como alguém consegue jogar tão mal.",
  "Vendo se consigo vender sua vaga no jogo por um pacote de figurinhas.",
  "Aguardando que você saia desse transe e perceba que está quebrado.",
  "Seu peão está pedindo asilo político no meu lado do tabuleiro.",
  "Calculando a taxa de permanência nessa tela de espera.",
  "Vendo se consigo comprar seu silêncio com uma nota de R$ 1 falsa.",
  "Seu império tem a estabilidade de um pudim no terremoto.",
  "Aguardando você parar de fingir que sabe o que está fazendo.",
  "O banco avisou: seu nome está no SPC do Monopoly.",
  "Vendo se consigo trocar sua próxima jogada por um chiclete mascado.",
  "Sua dignidade financeira foi vista saindo pela porta dos fundos.",
  "Aguardando o desfecho trágico da sua tentativa de ser rico.",
  "Vendo se o banco aceita pagamento em orações e promessas.",
  "Seu oponente já se aposentou e você ainda está na primeira rodada.",
  "Aguardando que os dados decidam ser cruéis com você de uma vez.",
  "Vendo se consigo hipotecar seu futuro para pagar meu próximo hotel.",
  "Sua conta bancária é uma obra de ficção científica.",
  "Aguardando o momento em que você vai pedir arrego.",
  "Vendo se o tabuleiro tem um botão de 'Ejetar Jogador Falido'.",
  "Sua vez demora tanto que a inflação já dobrou os preços.",
  "Calculando quanto de juros você me deve pela sua existência.",
  "Vendo se consigo alugar esse espaço na sua cabeça já que está vazio.",
  "Sua sorte foi comprada na promoção e veio com defeito.",
  "Aguardando você terminar de ler o manual que deveria ter lido ontem.",
  "O banco enviou uma coroa de flores para sua conta bancária.",
  "Vendo se consigo trocar sua dignidade por um par de dados novos.",
  "Seu império imobiliário é o motivo de piada no grupo de WhatsApp do banco.",
  "Aguardando você decidir se quer falir agora ou depois do lanche.",
  "Vendo se consigo vender seus restos imobiliários para o ferro-velho.",
  "Sua estratégia é tão secreta que nem você sabe o que é.",
  "Aguardando que o sistema operacional perdoe sua lerdeza.",
  "Vendo se o banco aceita pagamento em seguidores no Instagram.",
  "Seu peão está com vergonha de ser visto com você.",
  "Calculando o custo do enterro do seu império.",
  "Vendo se consigo comprar sua vez com uma moeda de chocolate.",
  "Sua sorte está escondida debaixo de um terreno que você não comprou.",
  "Aguardando você parar de olhar para o meu dinheiro com inveja.",
  "Vendo se o banco aceita permuta por marmita gelada.",
  "Seu império tem a sofisticação de uma barraca de limonada sem limão.",
  "Aguardando o grande final onde você entrega todas as suas cartas para mim.",
  "Vendo se consigo transformar sua falência num reality show.",
  "Sua conta bancária está pedindo socorro através de sinais de fumaça.",
  "Aguardando você descobrir que eu subornei os dados... brincadeira (ou não).",
  "Vendo se o banco aceita sua próxima jogada como garantia de risadas.",
  "Seu futuro no jogo é mais curto que coice de porco.",
  "Aguardando o momento em que a realidade vai bater na sua porta e cobrar aluguel.",
  "Vendo se consigo comprar sua paciência com um abraço e um 'sinto muito'.",
  "O jogo está apenas preparando o palco para a sua queda triunfal.",
  "Alimentando os hamsters que geram a energia dos servidores...",
  "Passando ferro nas notas de dinheiro para elas ficarem crocantes.",
  "Discutindo a relação com um dado que só quer dar o número 1.",
  "Limpando o lodo debaixo das propriedades do bairro industrial.",
  "Ensinando boas maneiras para o vira-lata que mora no terreno baldio.",
  "Tentando dobrar um mapa que teima em voltar à forma original.",
  "Retirando chiclete grudado debaixo das casas verdes.",
  "Negociando o preço do cafezinho com o gerente do banco.",
  "Pintando as cercas dos hotéis com uma escova de dentes.",
  "Ajustando o brilho das estrelas no céu do tabuleiro.",
  "Procurando o peão que caiu atrás do sofá da realidade.",
  "Desentupindo a pia da cozinha da mansão da Avenida Paulista.",
  "Colocando óleo nas engrenagens da Prisão para ela parar de guinchar.",
  "Expulsando pombos que decidiram morar na Estação de Trem.",
  "Trocando a lâmpada do poste da última rua do mapa.",
  "Conversando com a inteligência artificial sobre o sentido da vida imobiliária.",
  "Varrendo o pó de diamante que caiu da última carta de sorte.",
  "Afiando as pontas do peão de ferro para ele não escorregar.",
  "Costurando o bolso furado do banqueiro para o dinheiro parar de sumir.",
  "Regando as plantas de plástico das casas de luxo.",
  "Tentando descobrir quem deixou uma caixa de pizza no terreno vazio.",
  "Treinando para ser um magnata enquanto uso chinelos e meia.",
  "Limpando a fumaça das chaminés das fábricas para não poluir o código.",
  "Removendo o mofo dos contratos guardados no cofre desde 1935.",
  "Fazendo carinho no servidor para ele não esquentar muito.",
  "Organizando a fila de fantasmas que querem assombrar o tabuleiro.",
  "Traduzindo o manual do jogo para a língua dos dados.",
  "Dando banho no gnomo de jardim que guarda o banco.",
  "Avaliando se o ar que circula no jogo deve ser tributado.",
  "Enchendo o pneu do carrinho que transporta as notas de cem.",
  "Verificando se as nuvens do cenário são feitas de algodão doce.",
  "Pedindo desculpas para os dados por ter jogado eles com muita força.",
  "Limpando as marcas de café que os jogadores deixaram no asfalto virtual.",
  "Tentando entender por que o peão de chapéu é tão arrogante.",
  "Lustrando a cartola do Sr. Monopoly com flanela de seda.",
  "Contando quantos pixels existem entre a riqueza e a sarjeta.",
  "Escondendo o controle remoto que muda as regras do jogo.",
  "Avisando ao banco que a impressora de notas está sem tinta.",
  "Removendo a gravidade de algumas casas para ver o que acontece.",
  "Tirando selfies com o peão de dedal.",
  "Discutindo filosofia financeira com um sapato de ferro.",
  "Tirando a areia que entrou nos rolamentos dos dados.",
  "Pedindo autorização para a fada dos imóveis para subir o aluguel.",
  "Monitorando o humor das capivaras que atravessam o tabuleiro.",
  "Limpando o histórico de navegação do navegador do banco.",
  "Tentando fazer o peão de navio navegar numa poça de suco.",
  "Ajustando o fuso horário entre a casa inicial e a última propriedade.",
  "Verificando se o seguro contra desastres naturais inclui 'mau perdedor'.",
  "Dando corda no relógio de cuco da prefeitura do jogo.",
  "Penteando o bigode do magnata que ilustra as cartas.",
  "Retirando formigas que confundiram as notas de dinheiro com açúcar.",
  "Procurando a tampa da caneta que assina as hipotecas.",
  "Varrendo o azar para debaixo do tapete do tabuleiro.",
  "Tentando convencer o sistema que o número 7 é apenas um boato.",
  "Calculando a velocidade média de um peão com pressa.",
  "Limpando o suor frio dos jogadores da memória RAM.",
  "Avisando ao síndico que tem um jogador parado há muito tempo.",
  "Verificando se a Prisão tem café quente para os detentos.",
  "Lustrando as moedas que foram usadas no jogo anterior.",
  "Procurando um atalho que leve direto para a conta bancária do vizinho.",
  "Tentando fazer o peão de ferro flutuar na base da força de vontade.",
  "Consultando o horóscopo das casas verdes.",
  "Pedindo para o banco não contar as moedas tão alto.",
  "Limpando a poeira dos meus sonhos de ser bilionário.",
  "Ajeitando o nó da gravata invisível do meu avatar.",
  "Tentando descobrir onde o banco esconde os bônus de Natal.",
  "Escrevendo poemas românticos para o peão de cachorrinho.",
  "Lavando a louça acumulada nas mansões abandonadas.",
  "Ajustando a resistência do ar para os dados voarem melhor.",
  "Verificando se as notas de dinheiro têm cheiro de papel novo.",
  "Tirando o peão da tomada para ele não viciar.",
  "Conversando com as árvores do cenário sobre a alta dos juros.",
  "Limpando a lente do telescópio que vigia os adversários.",
  "Tentando dobrar o tempo para a minha vez chegar logo.",
  "Colocando etiquetas de 'frágil' nos jogadores que estão perdendo.",
  "Regando os pixels para eles não desbotarem.",
  "Tentando explicar para o banco que gratidão não paga dívida.",
  "Procurando o dono da carteira perdida no meio do tabuleiro.",
  "Limpando o vidro da tela para você ver o prejuízo com clareza.",
  "Tentando fazer o peão de dedal costurar as feridas da economia.",
  "Pedindo para o sol do cenário brilhar um pouco mais pro meu lado.",
  "Verificando se a grama do vizinho é mesmo mais verde no digital.",
  "Limpando as migalhas de pão que caíram no banco de dados.",
  "Tentando entender a psicologia de um dado viciado.",
  "Escondendo as cartas de azar no fundo da gaveta.",
  "Dando banho de loja no peão que está na sarjeta.",
  "Calculando quantas calorias um peão queima ao dar a volta no mapa.",
  "Procurando o parafuso que soltou da inteligência artificial.",
  "Tentando fazer o peão de carro andar sem gasolina.",
  "Verificando se o banco tem moedas para troco de um bilhão.",
  "Limpando a graxa das mãos depois de consertar o servidor.",
  "Tentando equilibrar os dados um em cima do outro.",
  "Perguntando ao destino se ele aceita suborno em moedas de prata.",
  "Lustrando os olhos do peão de cachorro para ele enxergar a sorte.",
  "Varrendo as promessas não cumpridas dos jogadores antigos.",
  "Tentando fazer amizade com o algoritmo do azar.",
  "Limpando o suor dos dados antes do próximo lançamento.",
  "Ajeitando a gola da camisa do sistema operacional.",
  "Procurando o botão de 'ficar rico instantaneamente'.",
  "Aguardando o sinal verde do universo imobiliário.",
  "Tentando desembaraçar o fone de ouvido que parece um ninho de mafagafos.",
  "Procurando a chave que estava na minha mão há dois segundos.",
  "Explicando para o vizinho que o barulho de ontem era só eu tropeçando no ar.",
  "Limpando o histórico de buscas porque ninguém precisa saber minhas dúvidas às 3 da manhã.",
  "Tentando fechar a calça que servia perfeitamente antes do final de semana.",
  "Aguardando o café esfriar enquanto encaro o vazio existencial da cozinha.",
  "Calculando se vale a pena levantar para pegar o controle ou viver sem TV.",
  "Lutando contra o lençol de elástico que insiste em soltar da ponta da cama.",
  "Pedindo desculpas para a quina da mesa depois de dar uma topada nela.",
  "Tentando entender por que a fatura do cartão é maior que a minha vontade de viver.",
  "Fingindo que estou lendo uma mensagem importante para não cumprimentar conhecidos.",
  "Ajeitando o cabelo na câmera desligada da reunião e percebendo que não tem jeito.",
  "Esperando o micro-ondas apitar como se fosse o evento do ano.",
  "Discutindo com o GPS que insiste que eu devo entrar num lago.",
  "Tentando descobrir quem é o dono do guarda-chuva que está na minha sala há meses.",
  "Limpando a tela do celular e percebendo que o risco é por dentro.",
  "Dando tchau para alguém que não estava dando tchau para mim.",
  "Planejando minha rotina fitness enquanto abro um pacote de salgadinho.",
  "Procurando o chinelo que o cachorro decidiu esconder em outra dimensão.",
  "Lendo o rótulo do shampoo no banho porque esqueci o celular fora.",
  "Tentando cancelar uma assinatura que exige que eu fale com três gerentes e um místico.",
  "Decidindo se a roupa no chão está suja ou 'usável por mais 5 minutos'.",
  "Aguardando a pizza chegar enquanto finjo que a fome é psicológica.",
  "Explicando para o gato que ele não pode comer o meu jantar.",
  "Tentando abrir um saco plástico de mercado com as mãos secas.",
  "Limpando o óculos e percebendo que a mancha é uma Digital de 2014.",
  "Contando quantas moedas faltam para eu me aposentar na próxima hora.",
  "Gritando 'Oi?' para alguém que falou algo que eu claramente não ouvi.",
  "Aguardando o ônibus que, segundo o app, chega em 1 minuto há meia hora.",
  "Tentando não rir em um momento sério e acabando fazendo um barulho de porco.",
  "Percebendo que esqueci a toalha só depois que liguei o chuveiro.",
  "Ajeitando a postura depois de passar 4 horas parecendo um camarão.",
  "Tentando descobrir de onde vem o grilo que decidiu morar no meu quarto.",
  "Limpando o teclado e descobrindo migalhas de um biscoito que nem existe mais.",
  "Pensando na resposta perfeita para uma discussão que aconteceu em 2019.",
  "Aguardando o vídeo carregar enquanto questiono minha escolha de operadora.",
  "Tentando assobiar para parecer natural enquanto faço algo errado.",
  "Lutando para tirar o preço de um presente sem rasgar a embalagem.",
  "Dando aquela conferida no espelho do elevador e me arrependendo.",
  "Tentando entender a letra da minha própria anotação de ontem.",
  "Aguardando o sono chegar enquanto meu cérebro revisa meus maiores micos.",
  "Calculando quanto tempo de sono eu teria se dormisse agora... e agora... e agora.",
  "Tentando colocar o pen drive do lado certo na terceira tentativa.",
  "Limpando o espelho e deixando mais manchado do que antes.",
  "Fingindo que entendi o que o médico escreveu na receita.",
  "Esperando a vontade de trabalhar aparecer (até agora nada).",
  "Tentando não derrubar o celular no rosto enquanto leio deitado.",
  "Decidindo se a comida na geladeira ainda é um alimento ou uma experiência científica.",
  "Aguardando o download terminar enquanto a barra de progresso me ignora.",
  "Tentando abrir um pote de palmito usando toda a minha força ancestral.",
  "Dando aquela olhadinha na geladeira só para ver se brotou algo novo.",
  "Tentando assoar o nariz sem fazer um barulho de trombeta.",
  "Esperando o sinal fechar só para eu poder atravessar sem pressa.",
  "Tentando lembrar se eu realmente tranquei a porta de casa.",
  "Limpando o ventilador e espalhando a poeira pelo universo inteiro.",
  "Fingindo que sei o que estou fazendo da minha vida.",
  "Aguardando a coragem para lavar a louça que está me encarando.",
  "Tentando explicar para a minha avó que o Wi-Fi não é um eletrodoméstico.",
  "Calculando se 5 minutos de soneca realmente mudam a minha vida.",
  "Tentando tirar um cílio do olho sem perfurar a córnea.",
  "Dando bom dia para o porteiro e ele respondendo 'Boa noite'.",
  "Aguardando o esmalte secar enquanto sinto uma coceira insuportável no nariz.",
  "Tentando não parecer suspeito na frente de um policial mesmo sem ter feito nada.",
  "Limpando a caixa de entrada de e-mails que têm 'Promoção' no assunto.",
  "Fingindo que estou prestando atenção enquanto penso no que vou jantar.",
  "Aguardando a água ferver como se o fogo fosse acelerar com o meu olhar.",
  "Tentando desvirar a gola da camisa sem parecer que estou lutando comigo mesmo.",
  "Decidindo se compro um curso ou uma pizza (a pizza ganhou).",
  "Aguardando o sol aparecer para eu fingir que vou caminhar.",
  "Tentando não pisar nas linhas da calçada por puro misticismo urbano.",
  "Limpando a poeira de cima da TV e percebendo que o mundo é feito de pó.",
  "Fingindo que a música que está tocando no meu fone não é vergonhosa.",
  "Aguardando a resposta daquela mensagem que eu enviei e me arrependi.",
  "Tentando fazer o papel higiênico rasgar na linha pontilhada.",
  "Dando aquela conferida no dente depois de comer algo com mato.",
  "Tentando subir a escada de dois em dois degraus para parecer atlético.",
  "Aguardando a chuva passar enquanto encaro o céu com desaprovação.",
  "Tentando entender por que eu entrei neste cômodo da casa.",
  "Limpando a câmera do celular com a camiseta e piorando tudo.",
  "Fingindo que o barulho na barriga foi o meu celular vibrando.",
  "Aguardando a segunda-feira passar (ela mal começou).",
  "Tentando tirar um pedaço de pipoca preso no dente há três dias.",
  "Decidindo se respondo 'kkk' ou 'hahaha' para não parecer seco.",
  "Aguardando a coragem de responder os 47 áudios pendentes no WhatsApp.",
  "Tentando não derrubar o controle remoto no vão do sofá.",
  "Limpando a mesa e percebendo que ela nunca esteve realmente limpa.",
  "Fingindo que o espirro alto foi de propósito.",
  "Aguardando a encomenda chegar e ouvindo passos fantásticos no corredor.",
  "Tentando não bocejar enquanto alguém me conta uma história longa.",
  "Decidindo se eu realmente preciso desse item que está no carrinho há meses.",
  "Aguardando o elevador enquanto aperto o botão repetidamente para ele vir mais rápido.",
  "Tentando não fazer barulho ao abrir um saco de salgadinho à noite.",
  "Limpando o suor da testa com um papel que esfarela inteiro.",
  "Fingindo que eu sabia que hoje era feriado/dia santo.",
  "Aguardando a motivação para arrumar o guarda-roupa (spoiler: não veio).",
  "Tentando colocar a linha na agulha como se estivesse desarmando uma bomba.",
  "Dando um pulinho para o lado para desgrudar a calça da perna.",
  "Aguardando o mundo girar enquanto eu tento me equilibrar nele.",
  "Tentando não rir da própria piada antes de terminar de contar.",
  "Aguardando o sistema carregar enquanto eu questiono minha existência."
];
